### ISSUE TITLE
Singularity allow "--userns"

### ISSUE THREAD

**Issue by KeyTals** [replikation/poreCov#101]
Hello,

We need provide "-u" or "--userns" while we run singularity on server installation. Is there any way to provide "-u" while running singularity mode of pipeline?

Keyur

**Comment by replikation** [comment]
hi @KeyTals  yes, it is possible to provide additional container flags to singularity. 

As a quick fix, without me changing the workflow itself you could try to merge the configuration file into poreCov via the `-c` flag (can't test this currently)

Would be like this:
````bash
# create the configuration file
echo "singularity.runOptions = '--userns'" > singularity.config

# merge the config into poreCov, e.g.:
nextflow run replikation/poreCov -c singularity.config   --fastq <stuff> -profile local,singularity
````

**Comment by KeyTals** [comment]
Thank you very much for the quick reply. No i am not getting the -u specific error.

Keyur

**Comment by replikation** [comment]
* nice, please report back if it everything works, I would like to add this to the readme as "troubleshooting" for others

**Comment by KeyTals** [comment]
Pipeline works fine. 

Thanks,
Keyur
