### ISSUE TITLE
latest pangolin

### ISSUE THREAD

**Issue by replikation** [replikation/poreCov#103]
find a way in nextflow to implement always the latest pangolin version in poreCov but report back pangolin and pangoleran version.

setup "weekly" or every x day pangolin docker images.

Solutions:
1) not sure if I can "URL-fetch" in groovy the latest container and put this in as a variable?
    * if not found use "latest" local available variant?
2) could use "latest" and "grep" version (similar to what nf-core is doing) - this way
   so auto build not just a version, build also a "latest" container. but would be good if the user can then specify the docker.
   
   
 dockerimage tag for daily build:    `nanozoo/pangolin:pangolinversion--pangolearnversion`  -- so its only pushed if "new"

**Comment by replikation** [comment]
* might be issues with singularity - lots of building
* alternatively i implement a "force latest pangolin" or something similar ?
* is nextflow auto pulling updated "latest" container?

**Comment by replikation** [comment]
* @hoelzer you can also always provide the latest pangolin version / container via `-c pangolin.config`

**Comment by hoelzer** [comment]
> 
> 
>     * @hoelzer you can also always provide the latest pangolin version / container via `-c pangolin.config`

ah okay, this would be then a way to not touch poreCov all the time. 

a) (auto)build the new container on Dockerhub
b) adjust the `pangolin.config` for config injection in the poreCov run

But then I also have to maintain a `pangolin.version` file - then i can also maintain the poreCov config ;)

**Comment by hoelzer** [comment]
uh @replikation maybe we can just do a 

```
pangolin --update
```

inside of the pangolin process? Afaik it will then check for the newest pangoLEARN version... but not sure if this will work inside of a Docker/Singularity container...

**Comment by replikation** [comment]
@hoelzer would do an update for each fasta file. could be done but still we need to get then the version
