### ISSUE TITLE
all_consensi vs all_consensus

### ISSUE THREAD

**Issue by oliverdrechsel** [replikation/poreCov#111]
This is a minor point.

i tried to check various times, but i couldn't find any support for consensi being the plural of consensus. 

one example could be:
https://www.wordreference.com/synonyms/consensus

**Comment by replikation** [comment]
thx for reporting

**Comment by hoelzer** [comment]
actually I think @oliverdrechsel was referring here to the output folder:

`results/2.Genomes/all_consensi/`

that could be renamed, right? And not mainly the figure. 

We just have to change this then also in our run and data collect script ;)

**Comment by replikation** [comment]
changed to -> `all_consensus_sequences`, will be included in the next poreCov release (probably 0.8.0 after the pangolin merge)

**Comment by hoelzer** [comment]
> changed to -> `all_consensus_sequences`, will be included in the next poreCov release (probably 0.8.0 after the pangolin merge)

thx!
