### ISSUE TITLE
Slurm support

### ISSUE THREAD

**Issue by KevinMenden** [replikation/poreCov#112]
Hi,

I've been trying to run the pipeline on a slurm cluster, using `-profile slurm,singularity`

This leads to the error message:
`No executor selected: -profile EXECUTER,ENGINE`

Looking at the code it appears that the error is thrown when slurm is selected, because "slurm" is not a valid option in this if-statement:

```nextflow
    if (
        workflow.profile.contains('nanozoo') ||
        workflow.profile.contains('ukj_cloud') ||
        workflow.profile.contains('local')
        ) { "executer selected" }
    else { exit 1, "No executer selected:  -profile EXECUTER,ENGINE" }
```

https://github.com/replikation/poreCov/blob/bc6b313a8d2dbbb45fb71e1cbc918311b25a9cdb/poreCov.nf#L83

Probably a bug? Or am I missing something?
Thanks for the help!

Cheers,
Kevin

**Comment by replikation** [comment]
@KevinMenden  hi thanks for reporting this issue. i added it to the current development branch which is near ready for release 0.8.0

You can try this out, if you want - but there might be still some bugs:

```bash
nextflow pull replikation/poreCov -r auto_pangolin
nextflow run replikation/poreCov -r auto_pangolin <commands> 
```

* i could incorporate directly changes and suggestions if something is missing for a clean slurm execution

**Comment by KevinMenden** [comment]
Hi @replikation , thanks!
I'll try it out and also wait for the new release :+1:
