### ISSUE TITLE
report - column header states mutations (on spike), but lists other genes 

### ISSUE THREAD

**Issue by oliverdrechsel** [replikation/poreCov#113]
I guess this is tiny cosmetics...

![grafik](https://user-images.githubusercontent.com/8122897/117318490-c217ed80-ae8a-11eb-8da2-f7a75ba72a4c.png)

The column header in the report list states mutations (in spike), but the data in the list also includes ORF1, N, ... 

Either the content of the table should be filtered for S protein only, or "(on spike)" needs to get removed.

**Comment by replikation** [comment]
hi

We show all the mutations but highlight the ones that are on the spike vai purple color, so its easier to check for them. or did i misunderstand the question?

best

**Comment by oliverdrechsel** [comment]
That's embarrassing.
Obviously I misunderstood the header and didn't get the highlighting.

Sorry.

Christian Brandt ***@***.***> schrieb am Do., 6. Mai 2021,
16:58:
