### ISSUE TITLE
Guppy CPU

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#115]
I just wanted to test the CPU feature for Guppy for some benchmarking but

```
Access to 'guppy_gpu.out' is undefined since process doesn't declare any output

 -- Check script '/home/hoelzerm/.nextflow/assets/replikation/poreCov/./workflows/basecalling.nf' at line: 24 or see '.nextflow.log' file for more details
```

It's really not an urgent thing bc/ GPU basecalling should be anyway recommended but maybe it's something rather simple to get fixed so people can also easily run the CPU version in the absence of any decent GPU.

**Comment by replikation** [comment]
ah i forgot about the cpu gpu switch in the help message.

**Comment by replikation** [comment]
@hoelzer should be solved now

**Comment by hoelzer** [comment]
awesome thx, will check tomorrow!

**Comment by hoelzer** [comment]
Runs now!

Ah, and CPU is using an older guppy version

https://github.com/replikation/poreCov/blob/master/workflows/process/guppy.nf#L76

Maybe there were issues w/ the newer one for CPU?

**Comment by replikation** [comment]
probably just not tested, thats all. Takes ages to do something via CPU. not even sure if someone is actually using it. okay ill push a hotfix

**Comment by hoelzer** [comment]
true, I'm just running a test on 200 cores just to highlight time diff between GPU and CPU... maybe I can then also run w/ the same GPU Guppy version to see if we can simply update that. But yeah, probably no one is ussing it
