### ISSUE TITLE
new pangolin version with new "column names"

### ISSUE THREAD

**Issue by replikation** [replikation/poreCov#118]
* https://github.com/cov-lineages/pangolin/releases/tag/v3.0
* might need a porecov update

**Comment by replikation** [comment]
* ping @DataSpott

**Comment by hoelzer** [comment]
The new pangolin v3 comes with a new tool `scorpio` as well. Basically, `scorpio` uses pre-defined sets of characteristic mutations to assign a _likely_ lineage. The assignments are prefixed with a "c", e.g. cB.1.1.7 which means B.1.1.7-like, basically. 

We observed that for example basal lineage assignments such as B.1 can be assigned to cB.1.525 via `scorpio`. We could think about adding another two columns to the report that show 

* `scorpio` assignment
* confidence score

but this might also cause some confusion. I think the pangolin output is anyway published somewhere so the experienced user could look this up any way?

**Comment by replikation** [comment]
we have the whole "pangolin" output in the results dir in the `3.Lineages_Clades_Mutations`

**Comment by replikation** [comment]
yeah, i would not put this into the final report for now to avoid confusion. Let's see how it develops.
