### ISSUE TITLE
Simple Read QC

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#12]
It would be good to have some qc of the input data. I think the easiest is a `NanoPlot` module. 

Maybe `PycoQC` as an option if the summary.txt is available. 

As a final output, it would be great to have a summary QC for all input samples/barcodes where one can immediately observe _strange_ samples.

**Comment by replikation** [comment]
true currently it's implemented in the basecalling only. but we can easily attach nanoplot - but a general summary, in the end, might be way more productive ("the final output")

**Comment by hoelzer** [comment]
Yes, it would be awesome to simply use MultiQC to summarize the NanoPlot output but atm it is not implemented finally:
https://github.com/ewels/MultiQC/issues/1074
