### ISSUE TITLE
Running pipeline on Bascalled/Demultiplexed samples

### ISSUE THREAD

**Issue by IFIK-virology** [replikation/poreCov#123]
Great tool!

We do real time GPU-based HAC basecalling and demultiplexing, however we have problems running PoreCov on folders with the structure "fastq_pass/barcode**".

Is there any option in the pipeline to use already demultiplexed samples?

**Comment by hoelzer** [comment]
Hi, 

we are doing this quite frequently using `--fastq_pass` as the input parameter. Maybe you just used `--fastq` (that was my mistake in the beginning). 

In addition, you can then also provide a sample sheet via `--samples` to automatically translate your barcode IDs into sample names.

**Comment by replikation** [comment]
hi and thanks,

* would be good to know what the problems are so we can fix them
* there is a `--fastq` input flag which allows to provide on fastq.gz or .fastq file per barcode 
  * so eg. `--fastq "barcode0[1-3].fastq.gz`  (basically one sample per file
* `--fastq_pass`  checks recursive if it can find `barcode??` dirs from guppy and if not it is redoing demultiplexing on all fastq files and then using these
* what is the command that you are using?

best

**Comment by IFIK-virology** [comment]
using --fastq_pass as the input parameter resolved it. Thnx!
