### ISSUE TITLE
Output QC

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#13]
I think currently there is no quality check of the generated consensuses? 

I suggest having at least some simple qc e.g.

* check for the number of N
* pairwise sequence identity to e.g. the Wuhan reference sequence

to automatically decide which samples yield _good enough_ consensus sequences for further processing. 

We could even simply implement a python script that people are working on right now:
https://gitlab.com/RKIBioinformaticsPipelines/president

Here, an input FASTA sequence is aligned to the Wuhan reference strain an a pairwise identity is calculated and reported in a tabular format.

**Comment by replikation** [comment]
agree we can sort the output a bit based on the alignment (wuhan is included here: https://github.com/replikation/poreCov/tree/master/data/reference_nCov19)
