### ISSUE TITLE
New Nextclade container, v0.9.2 

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#132]
I am just running v0.9.2 and it gets somewhat stuck in 

```
nextflow run replikation/poreCov -r 0.9.2 -profile local,singularity -w work --update --cachedir /scratch/singularity/poreCov --fasta '*.fasta' -resume
```

```
[92/416566] process > split_fasta (3)                               [100%] 4 of 4, cached: 4 ✔
[4f/2e1e16] process > determine_lineage_wf:pangolin (3)             [100%] 4 of 4, cached: 4 ✔
[85/fe1758] process > determine_mutations_wf:nextclade (2)          [  0%] 0 of 4
[b3/960487] process > genome_quality_wf:president (3)               [100%] 4 of 4, cached: 4 ✔
[a7/d1a9a0] process > genome_quality_wf:seqrs (2)                   [100%] 4 of 4, cached: 4 ✔
[b5/a2c894] process > rki_report_wf:rki_report (1)                  [100%] 1 of 1, cached: 1 ✔
[-        ] process > create_summary_report_wf:summary_report_fasta -
Pulling Singularity image docker://nanozoo/nextclade:0.14.4--30d35bd [cache /scratch/singularity/poreCov/nanozoo-nextclade-0.14.4--30d35bd.img]
```

I am not sure if this is Singularity-related. The nextclade container looks also kind small

```
-rwxrwxr-x 1 hoelzerm domänen-benutzer  58M Jun 29 12:17 nanozoo-nextclade-0.14.4--30d35bd.img
```

which might be fine. But anyway, 0.9.1 is working fine. 

I leave it running but it already stucks in the nextclade step now since 30min

Ah, and here the output of `.command.log`:

```
cat work/2a/9fa58ca411f4699a6ffd9073b61ae2/.command.log
Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at Timeout._onTimeout (/usr/local/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:934:2216)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

I also wonder a bit about the `.command.sh`:

```
 cat work/2a/9fa58ca411f4699a6ffd9073b61ae2/.command.sh
#!/bin/bash -ue
nextclade --input-fasta IMSSC2-0-2021-00378.fasta --output-tsv tmp.tsv
" > IMSSC2-0-2021-00378_clade.tsv
```

**Comment by replikation** [comment]
the size should be at around 180MB

**Comment by replikation** [comment]
* works on my end fine. did you rebuild the singularity container?

**Comment by hoelzer** [comment]
Works also w/ Singularity on your end? I removed the singularity container and also build it manually again

```
singularity pull docker://...
```

but this resulted in the same (small) image. I will try again

**Comment by hoelzer** [comment]
maybe that's related to the new way to build the Docker container? (`node:lts-alpine3.13` baseimage, `npm install ...`) which might interfere w/ the Singularity translation? 

However, if Singularity worked on your hand that would be strange :)

**Comment by replikation** [comment]
only tested docker, can you build a singularity image from a Dockerfile? we might want to really add some kind of singularity storage/hub to porecov

**Comment by hoelzer** [comment]
Thats the way we are running here the pipeline since the beginning :) Nextflow can take a Docker image and translate and store it as a Singularity image. Otherwiese, we could not use the pipeline on the Cluster here. Up to know, this worked fine. 

A Singularity storage Hub would be nice, how is nf-core actually doing this? I think they provide for some pipelines pre-build Singularity images.
