### ISSUE TITLE
nanopolish wf expecting medaka output

### ISSUE THREAD

**Issue by iferres** [replikation/poreCov#134]
Greetings! Hope you are doing well.

I think I found a bug. We were getting the following error when running the `--nanopolish` wf:
`Access to 'artic_medaka.out' is undefined since process doesn't declare any output`

Probably the bug is here:
https://github.com/replikation/poreCov/blob/ad970dce96da039e1e63ad66db0cdd92b070212f/workflows/artic_nanopore_nCov19.nf#L54

**Comment by replikation** [comment]
* hi good find and thanks for pointing out the faulty code
* this happened during the covarplot implementation
* the PR #135   should resolve this issue, you can test this and report back if everything is fine on your end:
  `nextflow run replikation/poreCov -b fix134 (...)`

thanks again

PS: i added nanopolish to the dry run so this will not happen again

**Comment by iferres** [comment]
Hi, sorry for the delay. My colleague just told me it worked, so thanks again for your time.
Bests!
Ignacio
