### ISSUE TITLE
Show available Guppy and Medaka models

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#142]
This came up while other ("non-nanopore-experienced") users were running poreCov. Besides the default models for guppy and medaka would it be possible to add information on the available models? Either via something like 

```
nextflow run replikation/poreCov --show_guppy_models --show_medaka_models
```

or in the README.md? The defaults are now w/ 0.10.0 the `sup` models for both but what if people get already fastq data as input. Or want to compare different models but are not sure what the exact `high` or `fast` model names are. In such a case, this would be helpful. 

Maybe (and if this is available) linking out to some other resources that have this information on guppy/medaka models would be already enough.

**Comment by hoelzer** [comment]
Ah and in this context it would be helpful to have both models also in the HTML report.

**Comment by RaverJay** [comment]
(I'm back from holidays)

What was used is asily available - will add to the report:
params.guppy_model
params.medaka_model

What models are available in general is dependent on what is in the guppy / ARTIC container and might change behind the scenes - I don't see an easy way to get this info?
Maybe make processes that run the containers, only to run `guppy_basecaller --list_workflows` ?
seems clunky

**Comment by hoelzer** [comment]
(wb!)

> What was used is asily available - will add to the report:
> params.guppy_model
> params.medaka_model

Great, thx.

> What models are available in general is dependent on what is in the guppy / ARTIC container and might change behind the scenes - I don't see an easy way to get this info?
> Maybe make processes that run the containers, only to run guppy_basecaller --list_workflows ?
> seems clunky

Yeah, agree. Could be just something to add to the "Troubleshooting" paragraph in the README? For us such stuff is basically clear, but for others just jumping w/ poreCov into ONT analyses they often feel lost w/ the correct models/params w/o even knowing what's available. So we could just add something like: click here to check available models or run xyz to get info.
