### ISSUE TITLE
Nanoplot error

### ISSUE THREAD

**Issue by karthick1087** [replikation/poreCov#149]
Hi Just trying with test data example using following command
nextflow run replikation/poreCov -profile test_fastq,local,docker -r 0.8.0
I am getting this error
read_qc_wf:nanoplot` terminated with an error exit status (127)

**Comment by replikation** [comment]
hi, 
* could u use a more recent version to check if the error still persists (e.e. 0.9.5)? 
* otherwise please attach the .command.log file here
* This file is located in in the work dir    (the error message should give you the path)

**Comment by karthick1087** [comment]
Thank you so much!!! Ran perfectly with 0.9.5

**Comment by hoelzer** [comment]
Great! @replikation/poreCov ***@***.***> then we should
likely also update the readme to show a newer version for the test command

**Comment by replikation** [comment]
done

**Comment by hoelzer** [comment]
Hi, thx for you interest in poreCov. How much cpu and ram does your machine
have?

Also, can you please check the work directory for the folder that runs the
NanoPlot process? In the terminal you can see the prefix of the
corresponding folder where the NanoPlot process runs, something like

ab/wu6h8s*

In this folder, you should find a .command.log file with maybe more
information about the error.

Also, you could try a newer release version of the pipeline (such as
0.10.2) but normally the release you tried should still be stable.
