### ISSUE TITLE
Nextclade update

### ISSUE THREAD

**Issue by ebarretoh** [replikation/poreCov#150]
Hi
Excelente work. Is it a possibility to update the Nextclade version?

**Comment by replikation** [comment]
hi, yes of course. we add it to the next release.

**Comment by ebarretoh** [comment]
Thanks Christian. May be, add an option like '--update' for pangolin

**Comment by DataSpott** [comment]
Greetings @ebarretoh 
The new nextclade-version 1.3.0 is now incorporated and can be accessed by using the branch-name "nextclade_docker_update" as argument for the [-r]-flag while running the command (e.g.: "nextflow run replikation/poreCov -r nextclade_docker_update ...").
Also while its working, I encountered some differences in the results compared to the former nextclade-version in the actual release. This will require further testing for now.

Regarding your suggestion: a [--update]-flag is incorporated and available in the official releases. The help-message states here: "--update        Always try to use latest pangolin lineage release [default: false]".
I hope this is the kind of function you suggested, but please feel free to let me know if you thought about something different :)

**Comment by replikation** [comment]
@ebarretoh yes makes sense to include nextclade into the --update flag to provide an always up-to-date version.
