### ISSUE TITLE
Illumina support

### ISSUE THREAD

**Issue by karthick1087** [replikation/poreCov#151]
Hi,
The tool is great. Can we use for Illumina paired end/Iontorrent PGM data as well. It will be helpful if it is extended to this two second generation platform starting from basecalled fastq reads to mutation profiling.

**Comment by replikation** [comment]
hi, its only available for nanopore data. however, it is possible to provide genomes from e.g. a Illumina-based assembly. (to generate the overview report) (via the `--fasta` flag)
a ready to use illumina pipeline can be found here for instance (https://gitlab.com/RKIBioinformaticsPipelines/ncov_minipipe)
also containerized. hope this helps

**Comment by karthick1087** [comment]
Great!!, thank you for the information.

**Comment by hoelzer** [comment]
@karthick1087 yes exactly and as @replikation stated already you might want to give https://gitlab.com/RKIBioinformaticsPipelines/ncov_minipipe a try, developed specifically for Illumina data. The default usage here is currently Snakemake+Conda and not Nextflow+Docker but we also provide a single Docker imagenif needed.

And we will continue to develop this pipeline for Illumina in the next months as well.

**Comment by karthick1087** [comment]
> @karthick1087 yes exactly and as @replikation stated already you might want to give https://gitlab.com/RKIBioinformaticsPipelines/ncov_minipipe a try, developed specifically for Illumina data. The default usage here is currently Snakemake+Conda and not Nextflow+Docker but we also provide a single Docker image if needed.
> 
> And we will continue to develop this pipeline for Illumina in the next months as well.

Thank you for the information. I tried the tool. Working well!!!!
