### ISSUE TITLE
Number of CPUs

### ISSUE THREAD

**Issue by karthick1087** [replikation/poreCov#154]
Hi, sorry to bother with third consequtive query. I am running the pipeline in the AWS EC2 cloud instance. Even after I supplied with --ncores=16, some of the  tools running with single cpu only, others are not engaged. Is there something that i can do to speed up the process.

**Comment by hoelzer** [comment]
Hi @karthick1087 firstly, I'm not super sure if we currently provide a ready-to-use AWS cloud profile. The pipeline was tested for GCP though. How did you start the pipeline, so what's you `-profile` parameter?

Besides, cloud compute resources are pre-configured here https://github.com/replikation/poreCov/blob/master/configs/nodes.config for each process. Passing options like `--cores` will not have an effect for cloud compute. You can also define your own configuration and inject this via `-c my_config`, for example when you want to adjust the cores and ram of certain processes.

**Comment by karthick1087** [comment]
Hi @hoelzer  The pipeline worked perfectly in AWS-EC2. My profile to run is local,docker. Especially, I feel nanoplot and kraken consuming time. Other process can able to utilise full/few cores. Even i tried with config file in AWS, I could not able to see any much difference in the timeline of completing the process. I feel like initial nanoplot QC takes lot of time.

**Comment by replikation** [comment]
hi @karthick1087 if you would like i could branch a AWS branch and we implement a generic AWS profile. i only have access to GCP and not AWS so i cant really test this wokflow.

**Comment by karthick1087** [comment]
> hi @karthick1087 if you would like i could branch a AWS branch and we implement a generic AWS profile. i only have access to GCP and not AWS so i cant really test this wokflow.

Hi thats great!!, If you Could branch for AWS. I will test the the work flow in AWS

**Comment by replikation** [comment]
@karthick1087 hi can you detail how you are currently starting was runs?

**Comment by hoelzer** [comment]
Hi!

--cores: Maximum cores used per process
--max_cores: Maximum cores run at all

E.g. --cores 4 --max_cores 8 will run at most two 4core processes in
parallel. We implemented this to prevent to many processes run in parallel
on large work stations with many cores that are also used by others.

However, these params only effect local execution (-profile local). For
cloud compute and on hpc (slurp, lsf,...) a pre-configured setup of cores
per process is run.
