### ISSUE TITLE
--min_depth function

### ISSUE THREAD

**Issue by omarkr8** [replikation/poreCov#158]
what does the min_depth option do exactly? I imagine it is independent of the min_coverage related to RKI?
I also do not see min_depth being referenced when starting the pipeline (unlike other parameters you can adjust).

**Comment by replikation** [comment]
* its the minimum read depth for the artic assembly. the default is a depth of 20x. 
* Every nucleotide below that will be masked to "N"
* ill add that to the references
* it was kind of useful if you have a bad sequencing run you can reduce the depth to at least find out what lineage it might be
* however the accuracy is not really good with so few reads to polish errors then.

**Comment by replikation** [comment]
* it is also described in the `--help`

`    --min_depth     nucleotides below min depth will be masked to "N" [default 20]`

**Comment by omarkr8** [comment]
Thanks, I did manage to find it in documentation. Just wasnt sure how the min_depth was being used.
So for bad runs, reducing the min_depth helps with reducing Ns at the cost of confidence in the consensus.

**Comment by replikation** [comment]
yes
