### ISSUE TITLE
nextflow/poreCov Error : Nout enough reads all samples, please investigate results/1.Read_quality

### ISSUE THREAD

**Issue by jepark-ebiogen** [replikation/poreCov#159]
Hello, I used nextflow/poreCov analysis, But These error keeps occurs.

## Command used
**nextflow run replikation/poreCov --fastq_pass fastq_test/ -r 0.9.5 --rapid -profile local,docker**

```bash
## when a process failed it looks like this:
executor >  local (13)
[3d/57e031] process > collect_fastq_wf:collect_fastq (1)              [100%] 1 of 1 ✔
[8d/b73b32] process > read_qc_wf:nanoplot (2)                         [100%] 3 of 3 ✔
[83/9e8c49] process > read_classification_wf:kraken2 (3)              [100%] 3 of 3 ✔
[a4/703e96] process > read_classification_wf:krona (3)                [100%] 3 of 3 ✔
[31/8e1d8f] process > artic_ncov_wf:filter_fastq_by_length (2)        [100%] 3 of 3 ✔
[-        ] process > artic_ncov_wf:artic_medaka                      -
[-        ] process > artic_ncov_wf:covarplot                         -
[-        ] process > determine_lineage_wf:pangolin                   -
[-        ] process > determine_mutations_wf:nextclade                -
[-        ] process > genome_quality_wf:president                     -
[-        ] process > genome_quality_wf:seqrs                         -
[-        ] process > rki_report_wf:rki_report                        -
[-        ] process > align_to_reference                              -
[-        ] process > create_summary_report_wf:plot_coverages         -
[-        ] process > create_summary_report_wf:summary_report_default -
Not enough reads in all samples, please investigate results/1.Read_quality
Could not generate any genomes, please check your reads results/1.Read_quality
```

> When I tried, The error occured the point starting nanoplot OR artic_ncov.
> Two error pointed out "**Not enough reads in all samples**" at the same time.
> And the process does not working anymore, just stopped with those warning sign.(not red one!)

## Actually, I tried this options.
nextflow run replikation/poreCov **-r 0.9.5** -profile local,docker \
  --update FALSE
--primerV, V1200
--minLength, 500
--maxLength, 1500
--rapid, TRUE

## More Context
Computer specs if you are running locally (not in the cloud or a cluster)

> OPERATING_SYSTEM = Ubuntu 18.04 LTS
> THREADS = default option
> RAM = 31GB RAM

What can i do for gettting normal output?
Could I change the sample data(.fastq.qz) files?
Please Let me know if you have the solution. 

Thank you!

**Comment by replikation** [comment]
this message only appears if the output of the "filter_fastq_by_length" process has no reads. you could reduce `--minLength, 500` to e.g. `--minLength 50` just to check if your reads are too short. how many reads are in your fastq files/sequencingrun?

**Comment by replikation** [comment]
e.g. what does the nanoplot figures in results/1.Read_quality say?

**Comment by replikation** [comment]
@DataSpott could it be a bug in relation to the --rapid flag and the `collect_fastq_wf:collect_fastq` ?

**Comment by jepark-ebiogen** [comment]
> this message only appears if the output of the "filter_fastq_by_length" process has no reads. you could reduce `--minLength 500` to e.g. `--minLength 50` just to check if your reads are too short. how many reads are in your fastq files/sequencing run?

Thank you for your support!
When I checked the reads of the input file(fastq.qz), one of the input files had a very short read counts.

Changing input file to another one enough read counts is good to solve this problem.

**Comment by jepark-ebiogen** [comment]
> nd the `collect_fastq_wf:collect_fastq` ?

And Actually, It was my company's project to give a solution to another company a analysis steps convenient.
They said All input files used rapid kit to analysis. So If I did not use rapid options, it occurs error. 
Maybe in this case, I thought rapid options does not affect bad result to this problem. :)

**Comment by jepark-ebiogen** [comment]
I really appreciate your help, again.
Thank you, and Have a nice day!

**Comment by replikation** [comment]
@jepark-ebiogen  we identified a bug when using `--rapid` and the `--fastq_pass`. If the fastq dir does not contain the default "barcode01" etc. dirs, we use guppy to re-demultiplex the files but currently the wrong arrangement file is used for this. this might cause the lack of reads.

**Comment by jepark-ebiogen** [comment]
My client said there were some problems.
I received the e-mail that mentioned the specific error be occured with using --rapid options && --fastq_pass method.
Was it caused by the error? or Is there a little probability it was related to this error?
What do i do for resolve this problem? 

Please let me know if you know how to solve this error.

**Comment by replikation** [comment]
hi, not really an error, i just set the default min length for the rapid option to 100. the next release will include this change. you can put this repository on "watch releases" then you get notification if a new release is available
