### ISSUE TITLE
Filter/ trim question

### ISSUE THREAD

**Issue by omarkr8** [replikation/poreCov#161]
Ive had some samples with consensus sequences 80% trimmed off, but going into the BAM files, there is some coverage throughout (but very little, this was a bad sample about 2k reads). 

1) which options can I use to adjust the trimming?
2) are the options listed in --help exhaustive?

thanks

**Comment by replikation** [comment]
hi not sure what the question is. you mean sequencing depth? 

--min_depth     nucleotides below min depth will be masked to "N" [default 20]

**Comment by omarkr8** [comment]
ah no i dont think it is a mindepth issue, because this specific round had mindepth 1.

i could send the consensus and alignment files, but they are 1gb +.
let me try to elaborate...

lets say I go into the consensus for a sample, i see strings of continous Ns. If i look into the alignment files, some of these will be due to zero coverage in that region. But sometimes I investigate the positions and find 5-10 decent reads; but they are still expressed as chunks of Ns in the consensus.

I would imagine that min_depth would not cause this issue. and i do not know why decent reads would get masked.
if you are still curious to see the data, i can send it over.

**Comment by replikation** [comment]
how does the alignment file look like (in the results the covarplot). or in other words you are sure that these "alignments" are not the primers that get trimmed later on?

**Comment by replikation** [comment]
can you give me the full command?
and what alignment files do you mean exactly?

**Comment by omarkr8** [comment]
the command I use is:
nextflow run replikation/poreCov --fastq_pass inputfolder --samples sample_names.csv \
   --primerV V3 --min_depth 1 --output outputfolder\
	 -profile local,docker -r 0.9.5

the alignment files im refering to are the _sample.primertrimmed.sorted_ BAM genome assemblies in 2.Genomes folders.
the reason im interested in those BAMs is to **check which reads were used to generate the consensus**. Correct me if im wrong, but the only fastq/a output the pipeline offers are in the filtered fastq, the consensus, and those BAMs.

**Comment by omarkr8** [comment]
I appreciate the insight. I did wonder if the artic pipeline had something to do with this. 
thank you for your patience.
