### ISSUE TITLE
Midnight primers, which settings

### ISSUE THREAD

**Issue by omarkr8** [replikation/poreCov#165]
I notice the 0.11.0 version added V4 primers, and I also see that the 1200bp primers have been around before this.

Im thinking the V4 primers are the ones used in the nanopore midnight kit EXP-MRT001 ?
does porecov account for the rapid barcoding step (variable read lengths)? I guess just adjusting length filters according would work.

sorry if this is written elsewhere and ive just missed it.

**Comment by replikation** [comment]
arent they using the  ARTIC V3  primers?

**Comment by omarkr8** [comment]
oh it seems the midnight kit uses the V1200 primers.
