### ISSUE TITLE
Classification strategy after initial read filtering

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#167]
Hi, 

this just popped up based on a recent run: 

* `kraken2` found here ~900 reads assigned to SARS-CoV-2 from a negative control
* however, after the read length filtering step only ~10 reads are left in the NC

Also, if we just `minimp2` the NC reads (unfiltered) to SARS-CoV-2 we hardly get any hit. 

Thus, it seems that some "junk" is just assigned to SARS-CoV-2 via `kraken2`.

It's also a bit confusing that later in the pipeline always the filtered read FASTQs are used but in the report the contamination percentages are based on the unfiltered files. 

Thus, proposal: move the `kraken2` step after the length filter. 

What do you think? I can also help w/ the implementation change if you are fine w/ such an PR.

**Comment by replikation** [comment]
yeah makes sense to add this i think. feel free to do a PR :)

**Comment by MarieLataretu** [comment]
Hi there, I'm on it and I was just wondering:
`kraken2` just classifies the reads, right? The SARS-CoV-2 reads are not filtered out and the reconstruction is done on the whole set of reads (`fastq_input_ch`)? (see https://github.com/replikation/poreCov/blob/master/poreCov.nf#L355-L368)

**Comment by replikation** [comment]
hi @MarieLataretu read filtering is currently within the artic workflow [here](https://github.com/replikation/poreCov/blob/cc0e35fd41fd9222d03ac084ebff732c7bf4b359/workflows/artic_nanopore_nCov19.nf#L13)

by this [process](https://github.com/replikation/poreCov/blob/master/workflows/process/filter_fastq_by_length.nf)

**Comment by MarieLataretu** [comment]
Yes, that's the read length filter. 
But what about the reads that are not classified as SARS-CoV-2. They are also used in the reconstruction, right?

So it's not: `kraken2 -> take only SARS-CoV-2 reads -> reconstruction`

**Comment by replikation** [comment]
* yes, this was more of a "future proof" decision to avoid that the classifier gets at some point outdated and removes reads that are actually important or viral reads for the assembly.

**Comment by MarieLataretu** [comment]
Okay - just doublechecking :)

**Comment by hoelzer** [comment]
Yes exactly. It's actually a bit different to other approaches (e.g.
covpipe @Marie) where people just continue with the set of sequences that
was classified as SC2. But what if the ref db gets outdated (looking at you
Delta...)

Honestly, I also think it makes not much difference especially for long
reads. The reads are anyway mapped to the (Wuhan) reference then and a 400
nt human read will not map. Thus, we just added kraken2 on top to the
general artic workflow to have these classification/contamination counts in
the report but still throw all the reads into the artic workflow.

But good you double checked, and thx that you are looking into it already!
;)

**Comment by replikation** [comment]
also kraken2 (as it needs more RAM) can fail in poreCov on low end computers, without compromising the whole pipeline and the user still gets a genome assembly + lineage
