### ISSUE TITLE
Add Scorpio

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#173]
`Scorpio` is used within `pangolin` to assign lineages based on pre-configured `constellation` files. E.g., this is used for Omicron right now until enough data is available for a pangoLEARN model. 

Thus, it would be also good for reproducibility to have `scorpio` and `scorpio constellations` versions in the report (like for `pangolin`, `pangoLEARN`, `Nextlclade`, ...)

```
scorpio --version
scorpio 0.3.14

scorpio -cv
constellations v0.0.24
```

**Comment by RaverJay** [comment]
This info is quite hidden in the pangolin docker, right?
Any ideas how to get it out elegantly?

**Comment by hoelzer** [comment]
How do you currently get it for pangolin and pangoLEARN? Via the container name? 

Yeah, otherwise I think one approach is to add a `get-scorpio-versions` process that just starts the `label pangolin` container and then executes

```
scorpio --version
scorpio 0.3.14

scorpio -cv
constellations v0.0.24
```

to store this in some variable or txt file that is then channeld to your reporting process?

**Comment by RaverJay** [comment]
Yeah the pangolindocker parameter variable contains both versions

An extra process is what I also just decided, on it

**Comment by RaverJay** [comment]
Got any Omicron data at hand for testing?

**Comment by hoelzer** [comment]
i send you an email (GISAID policies... not sure...)
