### ISSUE TITLE
Add parameter to publish more results

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#174]
From a user feedback: the output is nice but if some strange sample is included that one wants to investigate further (using the BAMs, VCF, intermediate files, ...) it would be great to not have to go through all the `work` folder structure. 

Suggestion: we could add some parameter like `--publish-all` that can be used to activate more publish options in the processes. Thus, one could easily use 

```
... -resume --publish-all
```

to rerun and just - w/o re-calc - publish more files from the `work` folders. E.g. in some "intermediate data" folder or so? 

That would users help to check for problems in their data.

**Comment by replikation** [comment]
* its usually just the artic stuff or?
* we could add this to publish dir vor the assembly and publish the whole thing?

**Comment by hoelzer** [comment]
yeah you are right, mainly all the ARTIC stuff.

You mean just adding this in general to publish? Many more files I guess which might be also confusing... or we just have a `09-all-artic-files` folder and just publish the whole artic pipeline output into that folder in general. In case someone needs to inspect stuff
