### ISSUE TITLE
ARTIC V4.1 primer scheme for Omicron

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#175]
We might need to add support for V4.1 soon:

https://twitter.com/Scalene/status/1466070415986544640

https://community.artic.network/t/sars-cov-2-v4-1-update-for-omicron-variant/342

**Comment by replikation** [comment]
we might want to implement also a "flexible" approach for a user to supply just a primer bed file?
otherwise, just copy V4 and add the primer bed to the dir :)
`--primerV` basically just specifies the primer dir to use which is located here: https://github.com/replikation/poreCov/tree/master/data/external_primer_schemes/nCoV-2019

therefore adding any dir and using the dir name in --primerV will work

**Comment by hoelzer** [comment]
k great!

> we might want to implement also a "flexible" approach for a user to supply just a primer bed file?
actually, this might be helpful for a few users as well, yes. Only the primer bed is needed, right? Assuming then the primer positions are based on the correct reference Wuhan FASTA, which is right now always the case basically

**Comment by hoelzer** [comment]
We will test V4.1 soon, so would be good to get the primer BED in poreCov. 

But yet can not find something here https://github.com/artic-network/artic-ncov2019/tree/master/primer_schemes/nCoV-2019

**Comment by hoelzer** [comment]
[Spike-in Pools ARTIC 4.1.pptx](https://github.com/replikation/poreCov/files/7717735/Spike-in.Pools.ARTIC.4.1.pptx)

**Comment by MarieLataretu** [comment]
Not quite sure, what this comment means, but the arctic guys are also on it:
https://github.com/artic-network/artic-ncov2019/issues/86#issuecomment-993893908

In the mean time, I have here a scheme file for V4.1: [nCoV-2019.scheme.bed.txt](https://github.com/replikation/poreCov/files/7718166/nCoV-2019.scheme.bed.txt)
Not sorted, just concatenated - not sure if this is important.

**Comment by hoelzer** [comment]
maybe that already does the trick, @MarieLataretu ! thx

Do you have time to add this as new primer kit to the pipeline? As @replikation wrote above, this should be relatively easy. 

The best would be of course to use the "official" files once this issue artic-network/artic-ncov2019#86 (comment) is resolved. Maybe lets wait until tomorrow and see if the files are added then to the ARTIC primer repo :)

**Comment by MarieLataretu** [comment]
Sure, I can do a PR!

As I understand poreCov, only the scheme file is used, right?

**Comment by replikation** [comment]
just add a folder like this:
https://github.com/replikation/poreCov/tree/master/data/external_primer_schemes/nCoV-2019/VarSkipV1a

primer bed file and the fasta and fai file (can be copied). the dirname is the name for the ``--primerV` flag.
seqrs is using the primer bed file
