### ISSUE TITLE
KrakenDB update

### ISSUE THREAD

**Issue by oliverdrechsel** [replikation/poreCov#178]
Hi,

we at covpipe are going to update the Zenodo KrakenDB. It may take a bit though.
Just FYI to avoid duplicated work, if you wanted to updated the DB as well.

cheers.

**Comment by replikation** [comment]
@oliverdrechsel  what is the status? i could add it to the new release we are currently preparing and testing

**Comment by oliverdrechsel** [comment]
Dear all,
finally i uploaded an updated version to the same entry in zenodo.
it took quite a while, sorry.

https://zenodo.org/record/6333909

**Comment by replikation** [comment]
thank you
