### ISSUE TITLE
--update does only update Pangolin or Nextclade ? 

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#181]
I'am not 100% sure about this but I started the pipeline today and the new pangolin container was pulled and used

 nanozoo/pangolin:3.1.17--2021-11-25

However, I then ended up with the pipeline using an older Nextclade container. I resumed the pipeline and now also the newest Nextclade container was pulled

 nanozoo/nextclade:1.7.0--2021-12-09

Due to how the update feature is implemented, can it be that in case both containers are updated that only one is pulled? Or was this just some typical edge case of mine? ;)

**Comment by replikation** [comment]
mh not really, it should execute both updates [together](https://github.com/replikation/poreCov/blob/55acad7e47743c6c0c8136f3667bd387dfd7a578/poreCov.nf#L254)

its 

1. check if dockerhub can be reached using exemplary the pangoling dockerhub page, [this](https://github.com/replikation/poreCov/blob/55acad7e47743c6c0c8136f3667bd387dfd7a578/poreCov.nf#L236)
2. if it can be reached extract the latest release name for nextclade and pangoling, [this](https://github.com/replikation/poreCov/blob/55acad7e47743c6c0c8136f3667bd387dfd7a578/poreCov.nf#L252)

these "latest names" are then printed to the terminal also

**Comment by replikation** [comment]
iam extracting from this page (https://registry.hub.docker.com/v2/repositories/nanozoo/nextclade/tags/) and the latest build docker container is the first one as its sorted by this date structure: "2021-12-12T01:24:15.740459Z"

**Comment by hoelzer** [comment]
Alright, yeah should work then. It might be also rare that we have updates of both containers - except when someone did not run and update the pipeline for a while (or a new VOC appears). We can also close this for now and just keep it in mind - let's see if this pops up again.
