### ISSUE TITLE
Add mid strand barcode detection to guppy

### ISSUE THREAD

**Issue by replikation** [replikation/poreCov#183]
via the following flag:

````
--detect_mid_strand_barcodes --min_score_mid_barcodes 50
````

**Comment by hoelzer** [comment]
Ah, by that one might recover reads that have a barcode in the middle, due
to some weird ligation?

**Comment by replikation** [comment]
yes

**Comment by replikation** [comment]
* less than 0.5 % more reads. this value could of course vary by experiments.
