### ISSUE TITLE
Omicron: report shows insertion S:A213AEPE although S:R214REPE is the (likely) correct one

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#184]
I just run porecov V0.11.5 with V4 (and V4.1, but same results) and got for two Omicron samples:

![image](https://user-images.githubusercontent.com/14393703/146591386-41abe46c-9b00-4b32-813b-0ee2938a786d.png)

This looked strange, so I used the reconstructed genomes with our tool covsonar that calculates and stores mutation profiles and here I get back S:R214REPE - which is also the insertion seen in 99.9% of Omicrons. 

I'm also pretty sure this worked ~2 weeks ago when you implemented it and I did a first test. Now assembled the same sample again but also get this wrong S:A213AEPE

So I am curious if this is an issue of the nt2aa translation from the Nextclade output @RaverJay ? Could be that Nextclade changed something (pretty sure the container updated the last weeks a few times)

**Comment by oliverdrechsel** [comment]
Would it be useful to use SNPeff instead of Nextclade for nt to aa
translation?
It works pretty fast, directly on vcf files and should be nice to parse.

Martin Hölzer ***@***.***> schrieb am Fr., 17. Dez. 2021,
20:59:

**Comment by hoelzer** [comment]
Yep @oliverdrechsel fair point, thx for mentioning again. So basically we could orientate on 

https://gitlab.com/RKIBioinformaticsPipelines/ncov_minipipe/-/blob/master/covpipe/rules/inspect_vars.smk

`snpEff` gets only the VCF as input bc/ there is a special version for SARS-CoV-2 (thus not even a reference FASTA is needed as long as the original Wuhan case stays ;) )

So I think @RaverJay question is if there is just some little index error due to some change in the Nextclade output or so or if it's more complicated and fragile and better we switch to `snpEff`

**Comment by RaverJay** [comment]
Looks exactly like they changed the reported position by 1

But if they are likely to change that around again we should go to
something more stable

Martin Hölzer ***@***.***> schrieb am Fr., 17. Dez. 2021,
22:38:

**Comment by hoelzer** [comment]
Yeah, then maybe snpeff we should implement. Should we deactivate the
insertion column or quick fix the 1pos of thing until we have this? Just on
a hot fix if people right now use the pipeline for omicron this might be
misleading

**Comment by MarieLataretu** [comment]
I'm not sure how `snpEff` could help us here, since the variants are only stated explicitly in the vcf file on nucleotide level and the html looks also not helpful.

[augur translate](https://docs.nextstrain.org/projects/augur/en/stable/usage/cli/translate.html) sounds nice, but I guess `Nextclade` uses that internally, because it's part of `Nextstrain`, so the problem with missing aa insertions wouldn't be solved.

**Comment by hoelzer** [comment]
Hm okay, I'm not experienced w/ `snpEff` so maybe @oliverdrechsel can elaborate a bit more on how we could easily add this to also get the amino acid positions of insertions? For me it sounded like you can provide `snpEff` a VCF file and then you get all changes in amino acid space? And because there is a special release for SARS-CoV-2 one does not even need to provide any further information (reference FASTA, ...)

Besides, @RaverJay implemented a quick fix end of 2021 that works so far and from what I have seen in the context of Omicron insertion. Thus, we could also close this issue and start a new one about `snpEff` implementation: if this is something to go for and to prevent further issues w/ `Nextclade`

**Comment by RaverJay** [comment]
I agree, let's organize it that way
