### ISSUE TITLE
add ARTIC v4.1 spike in profile 

### ISSUE THREAD

**Issue by oliverdrechsel** [replikation/poreCov#186]
Recently, you added ARTIC v4.1 profile https://github.com/replikation/poreCov/issues/175. Thanks for that. 
Our Sequencing department informed me that they are currently (and for foreseeable future) using a ARTIC v4 primer set that is spiked in with v4.1 primers. 

I don't know exactly, if ARTIC v4.1 drops primers that are contained in v4. If this is the case the spiked in sequencing contains primers that are unknown to the pipeline. Hence they are not clipped off. 

Would it be feasible to produce a v4.1 spike in profile that contains a non-reduntant union of v4 and v4.1?

cheers

**Comment by hoelzer** [comment]
Hi @oliverdrechsel yep, I think this is exactly what we (or better @MarieLataretu ) did: we used the default V4 BED file and added the coordinates for the additional V4.1 spike-in primer positions. 

You can find it here: 
https://github.com/replikation/poreCov/blob/master/data/external_primer_schemes/nCoV-2019/V4.1/nCoV-2019.primer.bed#L199

Currently, there is no "official" resource from the ARTIC network but this might come soon:
https://github.com/artic-network/artic-ncov2019/issues/86

Honestly, for me this is also not 100% clear but I think this is currently the best we can do:

* the additional primers are spiked-in so we have a mix of the original V4 primers and the new V4.1 ones
* thus, we can potentially get amplicons w/ all of these primers
* thus, we search for V4 and V4.1 primers and clip them

Once there is an official ARTIC Network primer BED file we might want considering to switch to that or basically compare it with the one we have right now set up and the primer spike ins the sequencing facility is using.

**Comment by MarieLataretu** [comment]
It sounds like you can do both!

> This time we are proposing to update the V4 to V4.1 using a patch consisting of 11 new primers which have been designed to be either used as a spike-in to existing V4 pools or as a replacement for the respective primers.

see [this post](https://community.artic.network/t/sars-cov-2-v4-1-update-for-omicron-variant/342).

For the moment, I think, it's fine to work with the spike-in variant, so you won't miss something.

**Comment by replikation** [comment]
can be closed?

**Comment by hoelzer** [comment]
> can be closed?

Yes, we solved it on Friday. But like mentioned here https://github.com/replikation/poreCov/issues/191 some notes about how the Bed file should look like would be good. And likely an option to just pass a user-defined Bed more easily into the pipeline, following some structure that fits the ARTIC workflow
