### ISSUE TITLE
Using consensus fasta type as PoreCov input

### ISSUE THREAD

**Issue by jepark-ebiogen** [replikation/poreCov#187]
Hello, poreCov!
I have a question for using the new type of data to nextflow/poreCov pipeline.
(First of all, I am newbie this domain-bioinfomatics-, But My boss said me that We use /poreCov pipeline, and input the nanopore Sequencing data to analysis bio problems. )

If I would like to use illumina Sequencing data to poreCov system, Could I use consensus data from .bam files those were composed by illumina seqeuncing results?

I am afraid to bother you because I know how poor this question is.
If you know about the answers, Please let me know.

Best Regards,
and Have a nice day.

- Jeongeun Park

**Comment by hoelzer** [comment]
Hi @jepark-ebiogen ! Thanks for your interest in our pipeline! 

The pipeline is only supposed to run with Nanopore input data to reconstruct consensus genomes. 

Or you can directly input already reconstructed genomes in FASTA format and poreCov will just generate the report (annotate lineages/clade, call mutations, ...). For this, you can use FASTA files from any sequencing technology, also Illumina. 

If you have Illumina raw read data (FASTQ), then please use another pipeline for the reconstruction (e.g. https://gitlab.com/RKIBioinformaticsPipelines/ncov_minipipe, ...)

**Comment by jepark-ebiogen** [comment]
Hi @hoelzer !!

Thank you for your kind reply.
Your answer is very useful to me.

I'll check those methods you mentioned.

Best regards,
Jeongeun Park

**Comment by hoelzer** [comment]
Pleasure, let us know if anything else is unclear. Closing this for now.

Happy Xmas!
