### ISSUE TITLE
Implement stable reporting of AA insertions, possibly snpEff

### ISSUE THREAD

**Issue by RaverJay** [replikation/poreCov#189]
Continued from #184 

If Nextclade implements aaInsertions as an output column we can just use that

**Comment by RaverJay** [comment]
Nextclade included aaInsertions to output (https://github.com/nextstrain/nextclade/pull/692)
I just need to integrate it

**Comment by RaverJay** [comment]
@replikation please build a new nextclade container so I can actually test :D

**Comment by RaverJay** [comment]
nvm there is no new release yet, I'll put of the PR anyway, it should work

**Comment by hoelzer** [comment]
Thx, yes best we wait until official release and bioconda recipe

**Comment by RaverJay** [comment]
Implemented in #198
