### ISSUE TITLE
Report classification as VOI, VOC, ... of lineages in results table

### ISSUE THREAD

**Issue by oliverdrechsel** [replikation/poreCov#190]
**Is your feature request related to a problem? Please describe.**
A colleague got a bit lost with the various VOCs, VOIs and VUMs from WHO and ECDC and their respective Pangolin lineage naming. 

**Describe the solution you'd like**
It would be cool, if porecov could classifiy the reported Pangolin lineages as "variant of concern". This might require a quite frequently updated table and would be a snapshot view as the VOCs are under constant re-evaluation.

**Describe alternatives you've considered**
A manual assignment is possible, but could be tedious due to the number of VOxs

**Comment by replikation** [comment]
@oliverdrechsel are WHO labels (the greek letters) by default already the VOC / VOI? Because these are currently shown and we could color code them like in orange with a legend explaining that highlighted Variants are VOC/VOI. This would of course not distinguish between VOC or VOI.  An automatic way would be indeed favorable.

This is the [nextclade definition table](https://github.com/nextstrain/ncov/blob/master/defaults/clades.tsv)

This is [the current WHO](https://www.who.int/en/activities/tracking-SARS-CoV-2-variants/) source for VOCs and VOI we could also link this to the final report. But i want to avoid writing some strange HTML parser.

**Comment by oliverdrechsel** [comment]
Writing a HTML parser for sure is something that should be avoided to not get crazy. 
On the WHO page there are VOC, VOI and VUM. 

I don't know, if there's anywhere out there a machine readable version of this information. I think @hoelzer once worked on something similar. 

If it's not possible to retrieve the data from anywhere, maybe this feature request could be dropped?

**Comment by replikation** [comment]
i keep the issue open, if we find a stable source to extract the data.

**Comment by hoelzer** [comment]
Good idea, but it's even a bit more complicated bc/ of sublineages. E.g. BA.1 should also classify as VOC (Omicron). Or AY.* is also VOC Delta. 

But I think there are machine-readable and updated resources we could hijack. I will check

**Comment by hoelzer** [comment]
I think we could use this:

https://github.com/3dgiordano/SARS-CoV-2-Variants/blob/main/data/variants.csv

From the Readme:

> Naming:
> The naming system used is a mix between the names denominated by WHO, the Pango Lineage system and some Nextstrain Clade names.
> 
> The project use the denomination of:
> 
> WHO/CDC/ECDC/PHE Variants of Concern (VOC)
> WHO/CDC/ECDC Variants of Interest (VOI)
> WHO Alerts for Further Monitoring (AFM)
> CDC Variants Being Monitored (VBM)
> ECDC Variants Under Monitoring (VUM)
> PHE Variants Under Investigation (VUI)

We could use some different color highlighting for 

* VOC
* VOI
* the rest {AFM, VBM, VUM, VUI}

**Comment by replikation** [comment]
question is now mostly how to add it to the HTML? color code the pangolin lineage by 3 colors?  VOC/VOI/nothing  ? want to avoid in adding to many columns and overloading the html

**Comment by hoelzer** [comment]
yes, agree. We already have quite some columns now (also with the insertions, ...) and this makes the table already quite long. So colors would be preferable I would say. Any wishes here, @oliverdrechsel ? I like the "ample" scheme style with maybe three colors or red/roange/none as suggested by @replikation

**Comment by RaverJay** [comment]
This info could also be added to the Pangolin column

**Comment by replikation** [comment]
@RaverJay what are you using for rendering? HTML usually supports "tabs" like in R markdown this way we can keep the important parts in one tab and the additional things in another?

**Comment by hoelzer** [comment]
Yeah, but just coloring the lineage name in the pangolin column would be
also a way and does not need additional columns

**Comment by RaverJay** [comment]
> 



> @RaverJay what are you using for rendering? HTML usually supports "tabs" like in R markdown this way we can keep the important parts in one tab and the additional things in another?
It's just html written 'by hand'
I think single paged has a lot of benefit though

> Yeah, but just coloring the lineage name in the pangolin column would be also a way and does not need additional columns
Imho writing **VOC** also helps a lot instead of only applying color (where people have to consult a legend first to know what is what)

**Comment by hoelzer** [comment]
> Imho writing VOC also helps a lot instead of only applying color (where people have to consult a legend first to know what is what)

true, +1
