### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by oliverdrechsel** [replikation/poreCov#191]
**Is your feature request related to a problem? Please describe.**
We're currently testing new Primer sets. As far as I can tell there is no documentation how to make porecov aware of new primer schemes that are not necessarily publicly available.

**Describe the solution you'd like**
Add a chapter to the documentation.

**Describe alternatives you've considered**
I've checked Readme to no avail.

**Additional context**
none

**Comment by hoelzer** [comment]
Hi @oliverdrechsel yes, fully agree. 

@replikation adding a short section about how to add primer sets via just cloning the repo and adding a new folder following a defined structure should be easy done? 

And then, as we discussed in the issue about the V4.1 primer addition, it would be good to think about an even easier way that users can just provide their own Bed file following a defined structure.

**Comment by oliverdrechsel** [comment]
It would be also nice to know if the bed file needs to fit any specifics.
We just recognised by trial and error (not sure, if all is true). 

- sorted by primer name, not position
- primer naming needs to be primer_1_LEFT, primer_1_RIGHT. Further extensions of the name seem to be tolerated.

**Comment by hoelzer** [comment]
... and 

* it also seems that column5 should have the information about pool "1" or "2"
* and something like:

```
*_56_LEFT_1
*_56_RIGHT_1alt
```

seems to fail when there is no

*_56_RIGHT_1

**Comment by hoelzer** [comment]
Hi @replikation , yes exactly, an optional "primer.bed" input parameter would be great. We could then just describe in the README what the structure is that needs to be used, basically following the ARTIC scheme. This would make testing w/ new primer sets more easily. One could then still use the latest `-r release` and just provide some `--custom-primer-bed foo.bed` or so
