### ISSUE TITLE
File name collision due to "." in the file name

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#193]
We run poreCov directly on some provided FASTQ files w/o checking the file names in detail. The pipeline failed then because of 

```
Process `create_summary_report_wf:plot_coverages` input file name collision -- There are multiple input files for each of the following file names
```

The issue is very likely the FASTQ file names:

* foobar_25.fastq.gz
* foobar_26.fastq.gz
* foobar2.4_2_27.fastq.gz
* foobar2.4_2_28.fastq.gz

and it seems that in the pipeline everything after the first "." gets removed. And then we end up with a channel that has non-unique entries `foobar2`. 

Can we fix this, or include something to test the file names before the pipeline really starts?

**Comment by hoelzer** [comment]
ah, nice @MarieLataretu , thx ;)

**Comment by replikation** [comment]
We can do basename instead of simplename. But then every sample name has
still the .fastq at the end.
There is also a filename collision if we have the same fasta headers.

Martin Hölzer ***@***.***> schrieb am Do., 13. Jan. 2022,
14:40:

**Comment by replikation** [comment]
closing this as its referenced in #192

**Comment by hoelzer** [comment]
Yes thx for closing, we just opened the issues simultaneously ;) lets continue the discussion in #192
