### ISSUE TITLE
Run --nanopolish on already basecalled data

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#194]
The help of poreCov states that it is possible to skip basecalling when providing FASTQ files and a sequencing_summary.txt via `--nanopolish`. However, for me, this results in:

```
Please provide a fast5 dir for nanopolish [--fast5]
```

Code used:

```
nextflow run replikation/poreCov -r 0.11.7 -profile local,singularity --cores 16 --max_cores 240 --krakendb GRCh38.p13_SC2_2021-02-08.tar.gz -w work-run382 --fastq_pass fastq_pass --update --output results-run382-nanopolish --primerV V4.1 --nanopolish sequencing_summary_run21-382.txt -resume
```

Is there maybe just a check still active that prevents this combination of inputs from running?

**Comment by replikation** [comment]
* --fast5 is missing. then it skips basecalling
* will improve help before release, added this info for search and closing this
