### ISSUE TITLE
Nanopolish mode: report requests

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#195]
These are just minor things, but when the pipeline is run in "nanopolish mode" this does not show up in the report, but might be interesting information. 

Also, when the pipeline runs w/ 

* `--fastq_pass fastq_pass`
* `--fast5 fast5`
* `--nanopolish sequencing_summary.txt`

no basecalling will be performed (which is correct and great!) but the report then states:

"Run type: Genome reconstruction and classification from raw sequencing data (fast5)"

which is not exact, right? Maybe we could write then:

"Run type: Genome reconstruction and classification from raw sequencing data (fastq) utilizing Nanopolish (fast5) information"

**Comment by RaverJay** [comment]
Yeah, the logic to detect the correct type of run gets rather complicated
will try to fix

**Comment by replikation** [comment]
or maybe just add the full command used to the report and good

**Comment by RaverJay** [comment]
sure, but can also be very convoluted

**Comment by RaverJay** [comment]
Closed by #197
