### ISSUE TITLE
Frameshift detection

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#199]
@replikation following up the discussion on BC: I think it's reasonable to put a terminal print warning about Omicron sequences missing many Spike mutations and showing `sup` basecalling and/or switching to Nanopolish as options to maybe fix that. 

However, instead, we could also implement a general check for frameshifts (FS). For example, this could be done via https://gitlab.com/s.fuchs/covsonar in two easy steps:

All reconstructed consensus sequences can be added to a covSonar database:

```bash
sonar.py add -f genomes.fasta --db mydb --cpus 8
```

Then, we can query this database via

```bash
sonar.py match --db mydb --only_frameshifts | awk 'BEGIN{FS=","};{print $1}' | grep -v accession > ids-frameshift.txt
```

which will give back all sequence IDs that have a frameshift. 

Now, we could additionally mark them in the report and/or print a message that one should be aware of that and maybe try basecalling with a higher accuracy model or switching to Nanopolish/Medaka. Or at least investigate the sequences if the frameshift is actually true. 

This would also help people w/ subsequent analyses and e,g, GISAID upload, ... 

What do you think?

**Comment by MarieLataretu** [comment]
(`nextclade` also reports the frameshifts in the `frameShifts` color)

**Comment by hoelzer** [comment]
> (`nextclade` also reports the frameshifts in the `frameShifts` color)

ah true - that we already have. ;) would be even easier than introducing another tool.

**Comment by MarieLataretu** [comment]
For the report I see two options:
- report frame shifts in a additional column and highlight it like mutations on the Spike
- don't report them, but highlight the sample (see #190)

**Comment by MarieLataretu** [comment]
I think, an additional column is the way to go. 
@RaverJay can you add the `frameShifts` column to the report, if you all agree @replikation @hoelzer ?

It's on amino acid level, but good enough for now.
