### ISSUE TITLE
Add CPU support for Guppy basecalling

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#20]
Compare: https://gitlab.com/RKIBioinformaticsPipelines/nanoqc/-/blob/master/modules/guppy.nf

We could provide for users w/o GPU access a CPU Guppy version. At the moment, I think, only GPU is supported.

**Comment by replikation** [comment]
cpu support is ultra slow or? we are talking weeks or?

**Comment by hoelzer** [comment]
> cpu support is ultra slow or? we are talking weeks or?

Yeah, super slow and only feasible on a large machine with 48 cores or so. But from what I know, people lacking a GPU are doing this right now :) Maybe I can easily move the code pieces linked above into poreCov and add --cpu flag.

**Comment by replikation** [comment]
yep ill add. just takes more time to validate if its running properly
