### ISSUE TITLE
Integration of VarSkip NEB primern

### ISSUE THREAD

**Issue by BoehmONT** [replikation/poreCov#201]
First, I like to thank you for developing this workflow for scientist who have no knowledge with bioinformatics.

To my questions, it is possible to integrate the VarSkip NEB primer from NEBNext ARTIC SARS-CoV-2 Companion Kit (E7660) to your workflow? The technical support of NEB told me for sequencing omicron samples, I should perform two libaries (one with V3 primer and one with VarSkip primer) and two barcoding steps. After sequencing with MinION I have to merge the two single sequences. 
Therefore, we should use the software Picard´s MergeSamFiles. Unfortunately, my knowledge of bioinformatics is strongly limtied. 
If the VarSkip NEB primer are available in your poreCov script, excist there also a tool for this problem?

**Comment by replikation** [comment]
hi,

we currently have the  `VarSkipV1a` implemented via the `--primerV` option. Did you try to run this already? or with V3? 

the main problem is that any SARS cov workflow (not just this one) needs all the primer Infos (usually stored in a .bed file) to remove them from the amplicons. so in your case, you probably need to combine these .bed files.

we want to add for the next release "custom" bed files for such edge cases as you have.

**Comment by replikation** [comment]
usually, i would recommend using the artic primer version 4.1 they address this omicron part directly or using the midnight primer (V1200) as they seem to be stable throughout the pandemic so far.

**Comment by replikation** [comment]
@hoelzer can you comment on the 4.1 ?    

the V1200 or midnight primers are sold via nanopore I think

**Comment by BoehmONT** [comment]
Thanks a lot.

**Comment by hoelzer** [comment]
Hey, I'm not ordering the wet lab stuff but can ask regarding V4.1 @BoehmONT ;)

**Comment by hoelzer** [comment]
Got answer: IDT now has V4 with V4.1 spike-in as a finished product but unfortunately no "pure" V4.1 @BoehmONT - hope that helps!

**Comment by bwlang** [comment]
I'm the designer of the VarSkip primers (designed in more conserved regions of the genome, hopefully for better resilience to mutations).  This approach worked well with beta, gamma, delta, mu etc, but omicron seems to have reset the definition of conservation in some regions.
https://primer-monitor.neb.com/lineages

VarSkip v2 was specifically modified to handle omicron variants (and all previous variants). Note that this is not a spiked-in mix containing old and new primers but a dedicated reformulation.

@oliverdrechsel was planning to add these to porecov via a PR I think. Meanwhile, it is possible to use the primers from I think https://github.com/nebiolabs/varskip . Let me know if you'd like me to make the PR instead.

**Comment by replikation** [comment]
@bwlang  to you have a bed file for the new primer set `VarSkip v2` we could then just simply add it like V1.

**Comment by oliverdrechsel** [comment]
Hi all,
it needed a little clean up to add the bed file to porecov. I'll issue a pull request today or tomorrow. 

cheers

**Comment by bwlang** [comment]
@replikation :Yep - it's available here:
https://github.com/nebiolabs/VarSkip/blob/main/neb_vss2.primer.bed

(v1a and VarSkip long are there too)

I thought this format would work - but maybe it needs a bit more love to meet porecov's standards.

I’ll try to get porecov working on a local VarSkip v2 dataset today.
I'm curious it  it will handle an ONT only TTTTT->TTTTTT issue (around position 5386) better than field bioinformatics.

**Comment by bwlang** [comment]
@oliverdrechsel : thanks for working on this!

**Comment by hoelzer** [comment]
@bwlang thanks for the information on the `VarSkip v2`, thats very helpful and thx @oliverdrechsel for preparing the PR!

A bit offtopic, but regarding your TTTTT->TTTTTT issue, actually the basecalling model might have the largest impact? Running `sup` instead of `hac` might help here as well, I could imagine. And/or switching from Medaka to Nanopolish within the ARTIC workflow (also possible via poreCov).

**Comment by BoehmONT** [comment]
First of all, I like to thanks everyone of you for your entire support. 

@hoelzer: sorry for asking, what is IDT?
@bwlang:  NEB technical support has recommended to use separate ONT barcodes for the V3 primer and VSS primer DNA libraries because the two libraries must be bioinformatically processed separately using the corresponding .bed file to remove the primer sequence from the amplicons. Subsequently the two  BAM files have to merge via Picard's MergeSamFiles to generate a comined consensus sequence for variant calling.

Is it still possible to work with the poreCov workflow? Actually, I am dependent on the poreCoV workflow because my bioinformatics knowledge is severely limited.

**Comment by BoehmONT** [comment]
Is a merge samfile included in the poreCov workflow? Or do further steps have to be taken to get standardized data for the RKI dashboard?

**Comment by hoelzer** [comment]
@BoehmONT IDT: https://eu.idtdna.com/pages/landing/coronavirus-research-reagents (at least I think so, srry bioinformatician speaking here that only passes information from the wet lab ;) )

**Comment by replikation** [comment]
* if you have a genome file you can provide these via the --fasta input and completely skip the genome assembly part and "just" do analyzing (e.g. `--fasta "*genomes.fasta"`)

**Comment by hoelzer** [comment]
... and I _think_ (not 100% sure, needs proper testing and double-checking your data e.g. via a Genome Browser) that you can also provide a BED file with mixed primer positions e.g. from V3 and VSS. In the pipeline, all these sequences will be checked and primer-clipped then. It's basically what we are doing w/ V4 and spike-in primers from V4.1 and this worked.

**Comment by BoehmONT** [comment]
@hoelzer do you mean, I could use for both primer V3 and VSS an identical ONT barcode for sequencing? So, if we use the poreCov workflow my sequences will be merged by your workflow?

**Comment by replikation** [comment]
* integrated
