### ISSUE TITLE
improve table style

### ISSUE THREAD

**Issue by replikation** [replikation/poreCov#207]
with all the features and columns the table stretches too much downwards (e.g. it's one line for each mutation currently). makes it a slight scrolling nightmare for > 40 samples

Proposals:
* reduce font sizes of mutations or group them into ORF1a: etc.
* combine results of %reads into one column
* combine Constellation(conflict)  and Clade into one column

**Comment by replikation** [comment]
* and yes i know we have tons of omicron spike mutations in the tables currently ;)

**Comment by hoelzer** [comment]
> * and yes i know we have tons of omicron spike mutations in the tables currently ;)

:) But yes, fully agree. It's nice to have all this information but the table gets super long.

**Comment by RaverJay** [comment]
imho you just need wider screens ;)

reducing font size is most feasible I guess?

**Comment by replikation** [comment]
but whats the maximum scale? its not automatically scaling on the x axis or?

**Comment by hoelzer** [comment]
Can we make the column with the mutations extendable? The table gets so long because we have especially with Omicron now so many mutations. Not sure if this is somehow possible with the python backend of the HTML report ;)

**Comment by replikation** [comment]
we might add a column "hide" feature like here: https://datatables.net/examples/api/show_hide.html

**Comment by MarieLataretu** [comment]
Hmm, maybe this is also a helpful element:

<details><summary>click here to expand</summary>

Hello World!

</details>

(`<details><summary>click</summary>content</details>`)

**Comment by replikation** [comment]
yeah. keep an overview but "hide" / "unhide" mutations

**Comment by RaverJay** [comment]
> Hmm, maybe this is also a helpful element:
> click here to expand
> 
> (`<details><summary>click</summary>content</details>`)

Was thinking about this one too

**Comment by hoelzer** [comment]
Can we then add a single button to hide/unhide all columns? Sometimes it's neat to scroll over the HTML even if it's long (e.g. so I discovered the BA.1 weirdos w/th the 5-vs-6-nt deletion). 

Also would be nice if one can still search via crtl-F e.g. "E484A" but I think this is also possible w/ the hiddn content

**Comment by RaverJay** [comment]
![image](https://user-images.githubusercontent.com/29630353/153002399-59420f3f-b5d2-48e7-b94e-7452666db3b4.png)

how about this?
