### ISSUE TITLE
Updated Midnight primer kit

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#209]
See: https://twitter.com/nanopore/status/1486386995924451332

So likely an updated BED is also needed then (V1200.1 ? :) )

**Comment by replikation** [comment]
any bed files?

**Comment by hoelzer** [comment]
not so far and that I am aware of

**Comment by omarkr8** [comment]
Perhaps not needed? the additional primer is an alternative to Pool B Left 28. so they occupy the same "amplicon slot". 

do degenerate primer beds exist?

**Comment by replikation** [comment]
ah good to know, thx @omarkr8  not sure about the degenerated primer beds
