### ISSUE TITLE
Variant calling doesn't seem to work with VarSkipV2

### ISSUE THREAD

**Issue by JaMaack** [replikation/poreCov#210]
Hi, I've been trying to run the pipeline with `--primerV VarSkipV2`. However, the run always prematurely stops at the variant calling step. The respective line reads `[71/0aad14] process > artic_ncov_wf:artic_medaka (23)  [100%] 23 of 23, failed: 23 ✔`.
It worked perfectly fine with the VarSkipV1 option and I haven't changed anything else.
I'm not really sure what the issue is, here.

**Comment by hoelzer** [comment]
Hi @JaMaack ! Thanks for using the pipeline, we just recently added `VarSkipV2` so need to look into this. 

@oliverdrechsel @MarieLataretu maybe there is still something misformatted with the BED file that does not work well with the ARTIC pipeline? Can you please compare it with the BED file that you were finally able to run? 

@JaMaack can you please provide the error log? E.g. via 

```
cat work/71/0aad14*/.command.log
```

that should give you information on one of the failed processes.

**Comment by oliverdrechsel** [comment]
Hi all

I'll send the bed file we used for our runs that worked well. Would be
nice, if we could swap it with the current one as I'm sure it works fine
then.

Cheers.

Martin Hölzer ***@***.***> schrieb am So., 30. Jan. 2022,
18:32:

**Comment by replikation** [comment]
@JaMaack could you try running poreCov via `-r customBED` the primer where now working on my end
* we merge this after some testing into a release
