### ISSUE TITLE
Pangolin v4.0

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#220]
There will be an update that changes the way pangoLEARN, etc... are used and aims to harmonize all that stuff into a single `pangolin-data` dependency:

> Another thing that will impact this is that pangolin 4.0 is due to be released this week at some point, and that will change the versioning system to be less convoluted than the current one.

> In pangolin 4.0, a new dependency pangolin-data will replace the current pangoLEARN and pango-designation dependencies. With this update, the pangolin-data version number will always be the same as the pango-designation version the model was trained on and the usher tree was built on. That removes the conflicting pango-designation versions reported and also removes the pangoLEARN dated versioning system, leaving only a single version that corresponds directly to the version of lineages used in the data.

https://github.com/cov-lineages/pangolin/issues/386#issuecomment-1082088001

We should be aware of that and might have to change some code (version numbers, report, ...) when this update happens.

**Comment by replikation** [comment]
yep this might need some adjustments on final report @RaverJay  but will simplify the overview

**Comment by hoelzer** [comment]
Example output of the new version:

https://github.com/cov-lineages/pangolin/issues/390

**Comment by hoelzer** [comment]
Great overview of the changes: https://cov-lineages.org/resources/pangolin/pipeline.html

**Comment by RaverJay** [comment]
Looks great, this will simplify things a lot

**Comment by hoelzer** [comment]
And a nice thread summarizing the main changes again

https://twitter.com/AineToole/status/1509876534529638411

**Comment by RaverJay** [comment]
@replikation when will the container be ready? :)

**Comment by hoelzer** [comment]
> @replikation when will the container be ready? :)

I guess at the moment when the new pango v4.0 is on bioconda :D

**Comment by replikation** [comment]
* no we are building from git directly to avoid delays @hoelzer. but the auto builds have a few checks to not cause an issue on poreCov (e.g. are the columns present - and it currently tags via pangolin and pangolearn version). this might be a bit annoying now to switch the whole thing in combination with porecov. (e.g. --update might break now older poreCov versions). SO i might need to fork and create a "pangolin4" container going forward or so. need to check first

**Comment by replikation** [comment]
@RaverJay i guess the html report creates an error if it cant get the correct versions?

**Comment by RaverJay** [comment]
> @RaverJay i guess the html report creates an error if it cant get the correct versions?
Yes, it will fail when the columns it needs are not there
