### ISSUE TITLE
export variant file (vcf)

### ISSUE THREAD

**Issue by oliverdrechsel** [replikation/poreCov#232]
**Is your feature request related to a problem? Please describe.**
Currently, the called variants are not exported to the results folder and are hidden in work folder.

**Describe the solution you'd like**
https://github.com/replikation/poreCov/blob/master/workflows/process/artic.nf may be modified to publish as well SNP_${name}.pass.vcf

**Describe alternatives you've considered**
none

**Additional context**
work folder tends to be quite bulky, hence we remove them soon after porecov is finished

**Comment by hoelzer** [comment]
Yes, I support that. The VCF is kinda often needed for some downstream stuff. And maybe we will also add some additional visualization soon where it would be anyway good to also provide the VCF for further checks.
