### ISSUE TITLE
Add new V5 ARTIC primer BED

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#238]
https://github.com/quick-lab/nCOV19/tree/main/v5.0

An adapted primer scheme for the most recent Omicron sublineages we can add.

**Comment by MarieLataretu** [comment]
* version 5.1 is under development, since 5 has also coverage issues with current variants

**Comment by hoelzer** [comment]
Ah great, good to know thx.

**Comment by MarieLataretu** [comment]
yes, I included V5 and V5.1 and will test it on V5 and V5.1 this/next week

since a few days there is also V5.2: https://github.com/quick-lab/nCOV19/tree/main/v5.2.0

**Comment by hoelzer** [comment]
And there is now v5.3.2.:

https://github.com/quick-lab/SARS-CoV-2/tree/main/400/v5.3.2_400

which we will test soon and needs thus to be integrated. I looked briefly at the BED and I think it needs some formatting to work with poreCov.
