### ISSUE TITLE
MinKNOW/Guppy update needs new model for R10.4.1 5 kHz

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#254]
In a recent MinKNOW/Guppy (v6.5.7) update, the sampling rate for R10.4.1 FCs was increased from 4 kHz to 5 kHz. In Guppy (v6.5.7), there is a new model for 5 kHz: `DNA r10.4.1 e8.2 400bps 5khz`

The corresponding Medaka v1.8.0 model for 5 kHz data is

`r1041_e82_400bps_sup_v4.2.0`

In the current ARTIC container we are using, Medaka is v1.7.2. Thus, I created a new ARTIC container w/ Medaka v1.8.0 and the most recent models:

`nanozoo/artic:1.3.0-dev--e22cdbc`

I suggest, after testing, adding that new container to the pipeline also to allow variant calling with recent Medaka models.

**Comment by MarieLataretu** [comment]
Thanks, @hoelzer!

The `medaka` processes fail at the moment, because `keras_preprocessing` is not found:
`ModuleNotFoundError: No module named 'keras_preprocessing'`

I added the full err file:
[tmp_medaka.err.txt](https://github.com/replikation/poreCov/files/11572665/tmp_medaka.err.txt)

**Comment by hoelzer** [comment]
Hey, thanks for testing @MarieLataretu !

Hm, I did not change anything else besides the Medaka version and everything installed successfully according to conda. 

I can try to add a 

```
conda install -c conda-forge keras-preprocessing
```

to the container build.

**Comment by MarieLataretu** [comment]
yeah, let's give it a try!

**Comment by hoelzer** [comment]
@MarieLataretu 

`docker pull nanozoo/artic:1.3.0-dev--784493e`

**Comment by hoelzer** [comment]
And I deleted already the non-working container `nanozoo/artic:1.3.0-dev--e22cdbc`

**Comment by MarieLataretu** [comment]
perfect, `nanozoo/artic:1.3.0-dev--784493e` worked!
