### ISSUE TITLE
Warning when execution report and timeline already exists

### ISSUE THREAD

**Issue by MarieLataretu** [replikation/poreCov#256]
This warning appears when the execution report and timeline already exist, e.g. when executing the pipeline multiple times:

```
WARN: Failed to render execution report -- see the log file for details
WARN: Failed to render execution timeline -- see the log file for details
```

The reports can be overwritten (https://www.nextflow.io/docs/latest/config.html#config-report) - or we introduce a timestamp to make the filename unique. 

I like the timestamp solution more - any objections?

**Comment by replikation** [comment]
timestamp is also fine. i added overwrite true to my workflows so far :)
