### ISSUE TITLE
The pipeline fails in artic_ncov_wf_artic_medaka

### ISSUE THREAD

**Issue by Bioloko** [replikation/poreCov#259]
The pipeline fails when starts runing artic_ncov_wf:artic_medaka, just jump these steps and finish the analysis without generating consensus sequences. But no error is shown in the console. im using a Mac (3,2 GHz Intel Xeon W 16 nucleus, 192 GB RAM)

## Command used

nextflow run replikation/poreCov -profile local,docker -r 1.8.3 --fastq '/Users/agaliana/Documents/Analisis_temporal/CORONA_230928/fastq_pass_test/catted_files/*.fastq.gz' --primerV V1200 --output /Users/agaliana/artic-ncov2019_poreCoV/CORONA_230928_test --cores 16 --memory 180 --update --rapid --medaka_model r1041_e82_400bps_fast_g632 --samples /Users/agaliana/artic-ncov2019_poreCoV/CORONA_230928_test/148_sec_pend.txt

**Comment by MarieLataretu** [comment]
Hi @Bioloko ,

could you maybe share the `.nextflow.log` and the `.command.log` file from `artic_medaka`'s work directory?

@hoelzer also had problems on a Mac (https://github.com/replikation/poreCov/issues/240), but I don't know if it is the same error.

**Comment by Bioloko** [comment]
Hi Marie,

Thank you for your mail. Im searching in the work folder of the failed process (77/71e0b6] process > artic_ncov_wf:artic_medaka (1) [100%] 1 of 1, failed: 1) and i cant see any .nextflow.log or .command.log i only see in addition of more files two logs (minion.log.txt) and vcfcheck.log). I attach you these files. 





[817747.vcfcheck.log](https://github.com/replikation/poreCov/files/12800367/817747.vcfcheck.log)
[817747.minion.log.txt](https://github.com/replikation/poreCov/files/12800368/817747.minion.log.txt)

**Comment by MarieLataretu** [comment]
I can't see something suspicious in `minion.log.txt` and `vcfcheck.log`.

`.nextflow.log` and `.command.log` are hidden files - maybe you have to change a setting in you file browser (on Mac `Shift + Command + period` should do it).

`.command.log` should be in the same directory as `minion.log.txt` and `vcfcheck.log`; `.nextflow.log` in the folder where you started the pipeline from

**Comment by Bioloko** [comment]
Hi Marie, 

Thank you for your mail. Finally i found the nextflow.log and command.log following your instructions. Please find attached the files.

Best

[command_log.txt](https://github.com/replikation/poreCov/files/12802956/command_log.txt)
[nextflow_log.txt](https://github.com/replikation/poreCov/files/12802965/nextflow_log.txt)

**Comment by MarieLataretu** [comment]
Hi @Bioloko , thanks for sharing!

From the log files, I'd say this issue is not related to #240 .

The error is a permission problem (last line of `.command.log`): `sed: couldn't open temporary file ./sedi4f8Y8: Permission denied`

Permission problems are often connected to Docker - would you be able to try it with Singularity (`-profile local,singularity`)? 

Else, I found [this note](https://www.nextflow.io/docs/latest/container.html#id3) for Docker usage on Mac, referencing [this tutorial](https://www.viget.com/articles/how-to-use-docker-on-os-x-the-missing-guide/)

**Comment by Bioloko** [comment]
Hi Marie,

Thank you for your time. Yesterday I was doing some tests with an ubuntu installed  virtual machine with the singularity profile and the analysis was performed successfully. I prefer to work with the Mac instead of te virtual machine, so maybe I have to try something related with permissions im going to check the links and see if I have any idea about.

Best

**Comment by MarieLataretu** [comment]
Hi @Bioloko ,

It's nice to hear that it worked with Singularity. 
Since I'm a Linux user, I can't offer you much support :/ 

I'd close the ticket as this is not a general issue, but feel free to discuss below (or reopen)!
