### ISSUE TITLE
Process retry in slurm profile

### ISSUE THREAD

**Issue by MarieLataretu** [replikation/poreCov#263]
Hi there,

currently, we ignore errors in the slurm profile:

https://github.com/replikation/poreCov/blob/0ff536fe01c2c2410e1b666c74a3bd43bd8dc287/nextflow.config#L131

I'd like to suggest to change this to:

```bash
process.errorStrategy = 'retry'
process.maxRetries = 1
```

Sometimes we see a process fail, because of HPC/SLURM hiccups. Usually, the exit status is 1 and the process runs through in the first resume run.

If you are fine with that, I'd make a PR 🙂

**Comment by hoelzer** [comment]
yes, good idea! +1
