### ISSUE TITLE
ukj-Flag to create mongoDB database entry and "filename support"

### ISSUE THREAD

**Issue by DataSpott** [replikation/poreCov#30]
Create Flag [--ukj]
- if used PoreCov uses the runinfo.txt-file provided in the run-directory
- for each barcode a string in runinfo.txt is give, containing following information about the sample:
    YYYYMMDD_Location_SampleID_Abbreviation

-> YYYYMMDD = Isolation-date
-> Location = Location of isolation
-> SampleID = internal sample ID
-> Abbreviation = Combination of letter S (= Survillance) or E (= Extern) with a number, describing that itś the x run of this sample (beginning at 0)

- parses this info  together with the rki-report, selected president-results, the primer-info and the analysing-date for each sample into one .csv-file for the upload into the database.

**Comment by replikation** [comment]
added
