### ISSUE TITLE
Only add genomes to final RKI FASTA and report.csv that meet QC criteria

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#31]
Question/Thought

I think currently in #28 all final consensus seqs are added to the `all_genomes.fasta` and `rki_report.csv`? 

Whereas this is fine (because then all information is in one place) we could also think of just writing sequences to these summary files that also meet the consensus QC. Otherwise, they might be anyway rejected when submitted to RKI. 

However, people might want to work also with sequences that don't meet the QC criteria internally and would otherwise miss them when they are not part of the summary files? 

And: when QC thresholds change, this must be also reflected in poreCov to not reject sequences that might actually pass the later QC

**Comment by replikation** [comment]
* oh good point. forgot about that. are the rki criteria correct now via president? or can I take straight from the "valid" column?

**Comment by replikation** [comment]
need to extract the "valid" sequence name. i think this can also be done based on channels

**Comment by hoelzer** [comment]
Should be fine for now, but might be subject to changes over the next days/weeks :) 

Maybe you can write to the summary rki folder: 

* genomes_valid.fasta
* genomes_invalid.fasta
* rki_valid_report.csv (that only contains then the IDs of the valid genomes?) 

By that, it should be also clear to the user what he can expect in every file?

**Comment by replikation** [comment]
good idea. yeah i think ill add that tomorrow or so

**Comment by replikation** [comment]
````
rki/
    valid/
        genomes_valid.fasta
        rki_valid_report.csv
    invalid/
        genomes_invalid.fasta
        rki_invalid_report.csv
````

**Comment by hoelzer** [comment]
@replikation is there still an output multi FASTA file that has ALL sequences? Actually, we would need that as well for downstream processing. However, for other uses the direct split into valid and invalid is good so what I can also do is:

```
cat rki/valid/genomes_valid.fasta rki/invalid/genomes_invalid.fasta > all_fasta 
```

for my downstream tasks
