### ISSUE TITLE
Update guppy

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#33]
Should we update Guppy GPU and CPU with the next PR? 

4.4.1-1--a3fcea3

**Comment by replikation** [comment]
could break things so i was avoiding that for now as the minimum cuda version is 11 for the new guppy, what do you have on your system?

**Comment by hoelzer** [comment]
Don't know how to check the version. I tried a couple of things but nothing gave me the version. 

```
nvcc --version
``` 

```
nvidia-smi
```

are not installed to get the version. 

We just installed NVIDIA driver version 460.

And yeah, of course if it runs stable that's fine. I just saw that there is a newer version.

**Comment by replikation** [comment]
* If you can't find nvcc, it should be in /usr/local/cuda/bin/ @hoelzer

**Comment by hoelzer** [comment]
thx but nope, no `/usr/local/cuda` folder on that machine
