### ISSUE TITLE
Filter FASTQ by length - report

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#35]
As an initial step, FASTQ files are filtered by length and if the file size is too small, the FASTQ is not processed any further. It would be good to have this somehow reported. 

E.g. I just tested a FAST5 run (V3 primers) that resulted in 24 barcoded FASTQ and it seems 9 of them were sorted out and not processed any further. 

It would be good to have a TSV with e.g. all IDs and a column that states which were sorted out due to low number of reads after filtering.

**Comment by replikation** [comment]
the size is so small for "removal" it should usually only remove barcodes that were falsely assigned via "guppy demultiplex" with the "one barcode only" option. so not sure if this would confuse more?

**Comment by hoelzer** [comment]
okay I see, let me do some checks and maybe you are right and we don't need this. It might be just confuse as well when people used 10 barcodes but only get 9 consensuses out (e.g. bc/ one barcode did not work well and produced only a handful reads). 

But in such a case, one can also go back to the pycoQC and check the assigned barcode distribution, ...

**Comment by hoelzer** [comment]
I set this to `wontfix` for now and will check some more data to decide if we necessarily need such an output table
