### ISSUE TITLE
Publish basecalled FASTQ files

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#36]
For downstream analyses often the basecalled FASTQ files are needed. 

Can we add a parameter e.g. `--publish_fastq` to activate publishing of `.fastq.gz` files after basecalling and demultiplexing?

**Comment by hoelzer** [comment]
Ahh, there is an output folder but it is called `0.Lineages` :) @replikation

**Comment by replikation** [comment]
* oh copy paste error, ill fix sorry

**Comment by hoelzer** [comment]
yep thx!
