### ISSUE TITLE
Centrifuge for human host contamination

### ISSUE THREAD

**Issue by replikation** [replikation/poreCov#39]
* add some metrics for human host contamination check (e.g. centrifuge)
* need to clip primers prior analysis

**Comment by replikation** [comment]
@hoelzer do you know which database you guys are using for this? i assume a DB with human AND the virus to allow for distinct classification between both (?)

**Comment by hoelzer** [comment]
@replikation 

4.3 Activating taxonomic Read Filtering
If necessary, reads not derived from SARS-COV-2 can be excluded.
Read classification is based on corresponding k-mer frequencies using a defined kraken2 database (--krakenDb).
A pre-processed database containing SARS-CoV2 and human genome sequences can be downloaded from:

https://zenodo.org/record/3854856

see https://gitlab.com/RKIBioinformaticsPipelines/ncov_minipipe
