### ISSUE TITLE
Installation from source without conda/singularity/docker

### ISSUE THREAD

**Issue by samfux84** [replikation/poreCov#5]
Hi,

Is it possible to install the poreCov workflow directly from source without using conda/singularity/docker?

Could you please publish a list of software/tools that are required for this workflow?

What I could figure out from the README is that guppy is required. On our HPC cluster we already have a guppy 4.0.11 installation with CUDA support. What else is needed?

Best regards

Sam

**Comment by replikation** [comment]
Hi @samfux84 

* using a local guppy installation can be done via adding  ` --localguppy` as stated in the `--help`
* I added to 2f4d2aea81198719da69459a01e95e91f2e0c5fe (the most recent master) the possibility to start nextflow without an "engine" like docker or singularity
   * do a `git clone` to try that out
* do `-profile local` to use native installations (it still prints to the terminal that no engine was selected but it won't exit the workflow)
* but I am not sure if it's possible to install everything without getting some dependency conflicts. Here is the list of tools used:

* [nextflow](https://www.nextflow.io/index.html)
* [artic protocoll](https://artic.network/ncov-2019/ncov2019-bioinformatics-sop.html)
* [augur](https://github.com/nextstrain/augur)
* [pangolin](https://github.com/hCoV-2019/pangolin)
    * [iqtree](http://www.iqtree.org/#download)
    * [mafft](https://mafft.cbrc.jp/alignment/software/)
    * [snakemake](https://snakemake.readthedocs.io/en/stable/index.html)
* [toytree](https://github.com/eaton-lab/toytree)
* [medaka](https://github.com/nanoporetech/medaka)
