### ISSUE TITLE
Keep alignment file

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#50]
For a more detailed variant calling QC it would be good as a first step to keep the alignment file. Best would be to have PSL format (I think like minimap2 directly can provide it)

**Comment by RaverJay** [comment]
Keep in mind there are now two alignment files, for each sample:
- one against the assembly for individual coverage plot
- one against the Wuhan reference to plot all together in the summary report

**Comment by hoelzer** [comment]
Good point. 

For actual variant QC of the reconstructed consensus it would be good to `publish` the

* one against the assembly for individual coverage plot

It is also debatable how much sense it makes to do such a variant QC in a similar way then for illumina, but we will investigate this at some point and thus it would be good to have the BAMs.

(actually... the BAMs are already in the 2.Genomes folder I think... so maybe this is alreay fine and we can close my request)

**Comment by replikation** [comment]
yep the bams for read against the genome (not wuhan) are in the genome folder
