### ISSUE TITLE
Optimize execution: multithreading, other tools, memory

### ISSUE THREAD

**Issue by RaverJay** [replikation/poreCov#58]
Should go through everything and check for efficient execution:

- CPU core usage
- better/newer programs (even awk etc have new and faster alternatives)
- minimap2 instead of bwa mem
- dynamically check for available memory?

**Comment by hoelzer** [comment]
Cool, and yes indeed, I also asked myself why `bwa` instead of `minimap2`? Might not have such a large impact because all is amplicon based (so no 20k reads) but still... :) so +1

**Comment by replikation** [comment]
* cpu stuff implemented in poreCov
