### ISSUE TITLE
Clean-up

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#59]
Is it possible to implement a parameter for a final clean-up after the pipeline finished? For example, it would be great to automatically get rid of the `-w work` folder once the pipeline finished succesfully. 

Might be possible via `onComplete`?

**Comment by replikation** [comment]
sounds interesting, like the idea.

**Comment by replikation** [comment]
cleanup might be difficult due to the "root" files generated via docker. the easier solution would be for people to point via flag or "config file" to a designated trash area?

**Comment by replikation** [comment]
also nextflow has i believe a build-in "remove workdir" function

**Comment by hoelzer** [comment]
> 
> 
> also nextflow has i believe a build-in "remove workdir" function

oh, this would be best then I think. An yes, of course, users can also point to `-w /scratch/` or `-w /tmp` or some other place where the data is deleted automatically eventually

**Comment by hoelzer** [comment]
> Actually there's a(n undocumented) feature to cleanup automatically the work dir adding cleanup = true in the config.

https://github.com/nextflow-io/nf-hack18/issues/3

**Comment by replikation** [comment]
oh nice find :)

**Comment by RaverJay** [comment]
Cleaning up after complete finish might be too late:

Just ran into this problem when running a 'heavy' test case of 54 fastqs.
With local executor, every kraken2 process writes an unpacked version of the krakenDB into the work folder.
This just filled up the disk until a kraken2 process died due to lack of space.

As the DB is not part of the process output, but only the kraken result ist - it should be fine to delete the unpacked copy after kraken2 is done?

**Comment by hoelzer** [comment]
@RaverJay true, that unpacked krakenDB can be just directly deleted in the kraken process to free-up storage while execution

**Comment by RaverJay** [comment]
Just hacked that in on github
https://github.com/replikation/poreCov/pull/67

**Comment by replikation** [comment]
* i add `scratch true` to "heavy disk" workdirs
* downside its not working properly on wildcards (eg. path("*.fasta")) but in case of kraken classification it works fine

**Comment by hoelzer** [comment]
> 
> 
>     * i add `scratch true` to "heavy disk" workdirs
> 
>     * downside its not working properly on wildcards (eg. path("*.fasta")) but in case of kraken classification it works fine

What does `scratch true` actually do? Just asking bc/ on HPCs depending on their configuration issues can come up if stuff is written to e.g. `/scratch` or `/tmp` per default. Or dies this automatically clean up work dirs where it is set to `true` (this would be awesome)

**Comment by replikation** [comment]
it is something internal for the nextflow command.run :

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /home/pditommaso/projects/rnatoy/work/ff/836e306cde436de39a0e2e5e4c8afc/.exitcode
  set +u
  [[ "$COUT" ]] && rm -f "$COUT" || true
  [[ "$CERR" ]] && rm -f "$CERR" || true
  (sudo -n true && sudo rm -rf "$NXF_SCRATCH" || rm -rf "$NXF_SCRATCH")&>/dev/null || true
  exit $exit_status
}

**Comment by replikation** [comment]
nextflow writes its own "scratch dirs"
