### ISSUE TITLE
Add reference genome coverage to the report

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#63]
One important metric for us is also the genome reference coverage. That means, how well is the Wuhan reference genome supported by the reads. As we anyway map the reads to the Wuhan reference this should be easy to calculate based on a BED file? 

In the Illumina pipeline, we use a coverage of at least 20X as a cutoff.

In the end, what I would like to have is basically: "reads from sampleXY cover 98.12345% of the Wuhan reference genome with at least 20X" as another number in the report. 

Secondly, based on that it would then be also easy to report a median coverage value (or do you think this is not as useful @replikation as we discussed in some other thread regarding nanopore amplicon sequencing)

**Comment by replikation** [comment]
the genome is 20x masked by "N" so the reconstructed genome itself represents > 20x coverage
and the identity is listed in the report also the number of mismatches. So not sure what the metric would give as useful feedback for the report (just want to avoid adding a barrage of infos)

**Comment by hoelzer** [comment]
Okay, thought about this again and I agree. Basically with that we also have a proxy of how well the Wuhan reference genome is covered by reads. So that's fine. 

The only other thing is: a mean/median coverage value bc/ I think this is needed often for submissions to databases such as GISAID, ... or?

**Comment by replikation** [comment]
all this thing should be in the president qc data I think. but would be to much for just the report
