### ISSUE TITLE
Report also Nextstrain INDEL positions

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#65]
A little thing: nextstrain also issues indel positions, could you add that w/ the other mutations or as an extra column?

**Comment by replikation** [comment]
oh its a separate column for this?. would make sense just to add it to the other ones. maybe with a highlight

**Comment by hoelzer** [comment]
Yep, seems so. Need to check the nextclade (srry I think I meant nextclade not nextstrain) output, but might be easy to grep and add

**Comment by RaverJay** [comment]
Do you mean the aaDeletions column?

**Comment by hoelzer** [comment]
> 
> 
> Do you mean the aaDeletions column?

This was actually a user request and I think `pangolin` is not reporting INDELs, or? So the idea would be to grep them from Nextstrain. For example, for B.1.1.7 there should be del69/70 and Y144del in the Spike. The deletions are super important for immune/ test escape and thus it would be of high value to have them in the report.

**Comment by RaverJay** [comment]
Should be. On it
