### ISSUE TITLE
Report percentage of Ns 

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#66]
Maybe also rather present %Ns rather than absolute numbers (will make it easier for people who have a hard time quickly dividing by 29902)?

Or both? I know that you are likely just taking the information from `president` so I could also escalate that to that tool so you could then just grep it from the `report.tsv`?

**Comment by replikation** [comment]
* sounds good like %(Number), @RaverJay what would be easier for you calculating this or president extension?

**Comment by RaverJay** [comment]
I had both in initially and found it confusing and removed it. Imho the number is easier to understand than the percentage.
Can add it back in if you want

**Comment by hoelzer** [comment]
@RaverJay would be nice to have the percentage Ns in again. It's what people are mainly looking for bc/ DESH, GISAID, ... have filters such as <x% Ns - thx!

**Comment by RaverJay** [comment]
On it

**Comment by hoelzer** [comment]
> 
> 
> On it

Always a pleasure working w/ you guys
