### ISSUE TITLE
Adjust percentage of classified reads 

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#71]
Currently, the report shows e.g. 100% SARS-CoV-2 and 0% human even if there are only 10 reads classified as SARS-CoV-2 (and the rest is unclassified). 

Thus, it is good to have the absolute numbers now as well but would it not be better to report the percentages in accordance with the Krona plot? E.g. 4 % SARS-Cov-2 if there is 96 % unclassified?

**Comment by RaverJay** [comment]
Agreed, on it
