### ISSUE TITLE
Update consensus QC

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#72]
`president` has a new version v0.6.0:
https://gitlab.com/RKIBioinformaticsPipelines/president/-/releases/v0.6.0

Besides some bug fixes that do not really affect `poreCov`, the order of the columns in the `report.tsv` was adjusted to be more intuitive (and not simply alphabetically sorted). 

However, I assume this will break `poreCov` when the container is updated w/o applying some changes to the code where metrics are extracted from the `report.tsv`?

**Comment by replikation** [comment]
yep this restructure is bad and needs to be tested properly

**Comment by RaverJay** [comment]
Summary report generation should be safe against column order changes, as data is read into a pandas dataframe and accessed via column names.
So if column names didnt change it should work

**Comment by hoelzer** [comment]
> 
> 
> Summary report generation should be safe against column order changes, as data is read into a pandas dataframe and accessed via column names.
> So if column names didnt change it should work

yep, just checked it. Only the JSON-extraction shell script relies on column numbers. I will do some tests and send a PR soon
