### ISSUE TITLE
Module and subworkflow structure

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#77]
A minor thing, but as sub workflows are used with the process code living here:
https://github.com/replikation/poreCov/tree/master/workflows/process

I think the processes such as:
https://github.com/replikation/poreCov/blob/master/modules/align_to_reference.nf

should also go in the `workflows` folder?

**Comment by replikation** [comment]
it currently sits there as it has no workflow :)

**Comment by hoelzer** [comment]
> it currently sits there as it has no workflow :)

ah yeah, I see :) Also fine for me, just wanted to issue this (feel free to close, nothing urgent)
