### ISSUE TITLE
nanopolish addition beside medaka

### ISSUE THREAD

**Issue by replikation** [replikation/poreCov#87]
* implement the nanopolish option also if fast5 was provided as input?

**Comment by hoelzer** [comment]
I think that would be really interesting, also to compare the final consensuses. 

We then just need to be aware of some slight differences in the processing of the files as described here:
https://artic.readthedocs.io/en/latest/minion/

See "Variant calling"

> Note: we use the $SAMPLE.trimmed.rg.sorted.bam alignment for the nanopolish workflow as nanopolish requires some leading sequence to make variant calls; we use the primer sequence for this purpose in order to call variants at the start of amplicons.

With medaka, the `$SAMPLE.primertrimmed.rg.sorted.bam` is used instead!
