### ISSUE TITLE
Summary report also in text table format

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#88]
It would be really helpful to get a table with the data instead of only an HTML file. This is because often content has to be copied or accessed programmatically per column of data.

The HTML report is great, but having the main content also written as a summary table would be awesome. 

@replikation I think you already write some JSON files for your auto database input? 

But for other users an XLSX (CSV) would be actually also good. 

@RaverJay I imagine it should be relatively easy to print out a dataframe that is anyway constructed for the HTML report also as a CSV or TSV? 

I put this w/ a prio high bc/ it would really help people that are already actively using the pipeline - but of course I know that there are also other busy things todo! ;)

**Comment by replikation** [comment]
without the plots should be doable i think

**Comment by hoelzer** [comment]
> 
> 
> without the plots should be doable i think

yep, really "just" the HTML table also as a csv/xslx (I think python also has functions to directly write a proper xlsx, which would be most usable format for many people)

**Comment by RaverJay** [comment]
> @RaverJay I imagine it should be relatively easy to print out a dataframe that is anyway constructed for the HTML report also as a CSV or TSV?

Only the formatted dataframe was made until now, but it is added now. see PR

**Comment by replikation** [comment]
tsv might be better for people who want o open via excel?

**Comment by hoelzer** [comment]
Actually, I think Excel can better work with csv? But not sure :D but as
Basti anyway puts out an xlsx as well I suggest to have a tsv instead of
the csv

Christian Brandt ***@***.***> schrieb am Fr., 26. März 2021,
23:10:
