### ISSUE TITLE
Warning when older version of pipeline is used

### ISSUE THREAD

**Issue by hoelzer** [replikation/poreCov#89]
Is it possible to add a warning when an older version of the pipeline is used? So that people can get automatically aware of new versions? Not sure if such a feature is maybe even part of Nextflow?

**Comment by replikation** [comment]
* its included [here](https://github.com/replikation/poreCov/blob/4382a3662fbcf269e317d4c6fbe763b75a5323af/poreCov.nf#L19) porecov exits if this minimal nextflow version is not found

**Comment by hoelzer** [comment]
No sorry, not the Nextflow version but the poreCov version. E.g. the newest release is 0.7.8 but the user runs 0.7.5. Would it be possible to then tell the user: there is a newer version, please consider updating

**Comment by hoelzer** [comment]
Otherwise users would always have to check the github page or via `nextflow info` if there are new version before running the pipeline. Not sure if this is possible

**Comment by replikation** [comment]
ah interesting.... should be possible. ill check that.
